"""Typed Max box properties.

GENERATED FILE -- DO NOT EDIT BY HAND.
Regenerate with: python scripts/gen_box_props.py

``BoxProps`` describes the keyword properties a Max box may carry, so that
``**kwds`` on the box-creating api can be typed instead of ``Any``. A
misspelled property name or a wrongly-typed value is then a type error
rather than a key silently written into the emitted ``.maxpat``.

Vocabulary: 53 curated + 793 from maxref
(attributes whose ``save`` meta-attribute is 1, i.e. the ones Max persists
into a patch) + 3 from py2max's own ``Box(...)`` calls
+ 1 seen only in the repository's .maxpat fixtures
= 850 properties.

``total=False`` throughout: every property is optional, which is what Max's
format means -- an absent key and a key set to null are different things.

Two dicts, differing only in which names they omit. A TypedDict key that
collides with a named parameter makes mypy report an overlap error *and stop
checking calls to that function*, so each is trimmed to its call sites:
``BoxProps`` for ``Box.__init__`` (five structural parameters, so ``text`` and
``outlettype`` stay in), ``TextboxProps`` for the factory entry points, which
take those as real parameters. The narrower flows into the wider, so the
factory can forward ``**kwds`` straight into ``Box``.
"""

from __future__ import annotations

from typing import Any, Dict, Sequence, TypedDict, Union

#: A Max atom: the loosest useful value type.
Atom = Union[str, int, float]

#: A Max time value: milliseconds, or notation such as "4n".
TimeValue = Union[int, float, str]


class BoxProps(TypedDict, total=False):
    """Properties accepted by ``Box.__init__`` beyond its structural args."""

    accentcolor: Sequence[float]
    accum: int
    accum_desat: float
    active: int
    active1: Sequence[float]
    activebgcolor: Sequence[float]
    activebgoncolor: Sequence[float]
    activecolor: Sequence[float]
    activedialcolor: Sequence[float]
    activefgdialcolor: Sequence[float]
    activeneedlecolor: Sequence[float]
    activesafe: int
    activeslidercolor: Sequence[float]
    activetextcolor: Sequence[float]
    activetextoncolor: Sequence[float]
    activetricolor: Sequence[float]
    activetricolor2: Sequence[float]
    addpoints: Sequence[Any]
    align: Atom
    allowdisabled: int
    allowdrag: int
    allowreorder: int
    allwindowsactive: int
    alpha: float
    amountcolor: Sequence[float]
    amxdtype: int
    annotation: str
    annotation_name: str
    appearance: int
    appicon_mac: str
    appicon_win: str
    applycolors: int
    applyfont: int
    arrow: int
    arrow_orientation: int
    arrowcolor: Sequence[float]
    arrows: int
    assistance: int
    attack: Union[float, int]
    attr: str
    attr_bpm: float
    attr_comment: str
    attr_display: int
    attrfilter: Sequence[str]
    audioframerate: float
    audioframesize: int
    auto_handle: int
    autoboxedit_patching: int
    autocompletionspace: int
    autoconnectusesmouseposition: int
    autoexport: int
    autofit: int
    autohint: int
    autolockunselected: int
    automatic: int
    automation: str
    automationon: str
    automouse: int
    autoout: int
    autopopulate: int
    autosave: int
    autoscroll: int
    autosize: int
    autosustain: int
    autowatch: int
    autowrite: int
    background: int
    bangmode: int
    basictuning: int
    bblend: int
    beats: int
    bgcolor: Sequence[float]
    bgcolor2: Sequence[float]
    bgfillcolor: Sequence[float]
    bgmode: int
    bgoncolor: Sequence[float]
    bgrulercolor: Sequence[float]
    bgstepcolor: Sequence[float]
    bgstepcolor2: Sequence[float]
    bgtransparent: int
    bgunitcolor: Sequence[float]
    bkgnddrag: int
    bkgndpict: str
    bkgndsize: int
    blackkeycolor: Sequence[float]
    blanksym: str
    blinkcolor: Sequence[float]
    blinktime: int
    border: int
    bordercolor: Sequence[float]
    bordercolor2: Sequence[float]
    bottommargin: int
    bottomvalue: int
    boundmode: int
    browsertext: str
    bubble: int
    bubble_bgcolor: Sequence[float]
    bubble_outlinecolor: Sequence[float]
    bubblepoint: float
    bubbleside: int
    bubblesize: int
    bubbletextmargin: int
    bubbleusescolors: int
    buffername: str
    bufsize: int
    bundleidentifier: str
    button: int
    bypass: int
    calccount: int
    candicane2: Sequence[float]
    candicane3: Sequence[float]
    candicane4: Sequence[float]
    candicane5: Sequence[float]
    candicane6: Sequence[float]
    candicane7: Sequence[float]
    candicane8: Sequence[float]
    candycane: int
    candycane2: Sequence[float]
    candycane3: Sequence[float]
    candycane4: Sequence[float]
    candycane5: Sequence[float]
    candycane6: Sequence[float]
    candycane7: Sequence[float]
    candycane8: Sequence[float]
    candymode: int
    cantchange: int
    cantclosetoplevelpatchers: int
    cefsupport: int
    cellheight: int
    cellpict: str
    cellwidth: int
    channelcount: int
    channels: int
    chanoffset: int
    chans: int
    checkedcolor: Sequence[float]
    checkforupdates: int
    classic_curve: int
    clearcolor: Sequence[float]
    clefs: int
    clickadd: int
    clickedimage: int
    clickinactive: int
    clickincrement: int
    clickmode: int
    clickmove: int
    clickmoveinactive: int
    clicksustain: int
    clickthrough: int
    client_rect: Sequence[float]
    clip: int
    clip_size: int
    clipdraw: int
    clipheight: float
    code: str
    coldcolor: Sequence[float]
    colhead: int
    collection: str
    color: Sequence[float]
    colorlabels: int
    colormode: str
    colorselectedtext: int
    colortheme: Atom
    colortitlebar: int
    cols: int
    columns: int
    colwidth: int
    comment: Any
    compatibility: int
    connectacrossdividers: int
    constrainduplicates: int
    constrainpointchanges: int
    contdata: int
    contrast: float
    contrastactivetab: int
    convertobj: int
    cool: int
    coolcolor: Sequence[float]
    copysupport: int
    crashrecovery: str
    curvecolor: Sequence[float]
    data: Any
    database: int
    datadirty: int
    dbdisplay: int
    dbperled: int
    debugqueuesize: int
    decodemode: int
    default_template: str
    defaultcachesize: float
    defaultglcontext: str
    defaultm4ldevicesfolder: str
    defaultpatchersize: int
    defaultprojectsfolder: str
    defer: int
    degrees: int
    delay: Union[float, int]
    depth: Union[float, int]
    description: str
    devpath: str
    devpathtype: int
    dialcolor: Sequence[float]
    dialmode: int
    dialtracking: int
    digest: str
    dimmedconnectionalpha: float
    direction: int
    direction_height: float
    directioncolor: Sequence[float]
    dirty: int
    disabledalpha: float
    disabledcolor: Sequence[float]
    disablefind: int
    display_flat: int
    display_range: Sequence[float]
    displayamount: int
    displaychan: int
    displayknob: int
    displaymode: int
    displaysinglechannel: int
    dividercolor: Sequence[float]
    dividers: Atom
    dividersize: int
    domain: float
    domainlabel: str
    dontreplace: int
    downarrow: int
    drag_window: int
    dragtrack: int
    drawline: int
    drawoffcolor: int
    drawpeakhold: int
    drawpeaks: int
    drawstyle: int
    drawto: str
    dsp_cpulimit: str
    dsp_driver: int
    dsp_inputdevice: str
    dsp_iovectorsize: str
    dsp_option1: str
    dsp_option2: str
    dsp_outputdevice: str
    dsp_overdrive: str
    dsp_samplerate: str
    dsp_siai: str
    dsp_signalvectorsize: str
    dstrect: Sequence[int]
    duration_active: int
    dynamic: int
    editing_bgcolor: Sequence[float]
    editlocked: int
    editlooponly: int
    editor_rect: Sequence[float]
    elementcolor: Sequence[float]
    embed: int
    emptycolor: Sequence[float]
    enable: int
    enabled: int
    enablednotes: Sequence[Atom]
    enabledrag: int
    enableglobalcontext: int
    enablehscroll: int
    enablesprites: int
    enablevscroll: int
    erase_color: Sequence[float]
    exclusive: int
    expansion: str
    export_dpi: int
    exportfolder: str
    exportname: str
    exportnotifier: str
    exportscript: str
    exportscriptargs: str
    externaleditor: str
    extra1_active: int
    extra1_max: int
    extra1_min: int
    extra1_signed: int
    extra2_active: int
    extra2_max: int
    extra2_min: int
    extra2_signed: int
    extra_thickness: float
    factorycontent: int
    fblend: int
    fgcolor: Sequence[float]
    fgdialcolor: Sequence[float]
    file: str
    filekind: str
    filename: str
    fillhorizontalspace: int
    filternodeschanges: int
    filtertext: str
    flagmode: int
    floateditorwindow: int
    floatoutput: int
    focusbordercolor: Sequence[float]
    folderslash: int
    followglobaltempo: int
    followlivetheme: Atom
    fontface: int
    fontlink: int
    fontname: str
    fontsize: float
    forceaspect: int
    forcejwebrendermode: int
    formant: float
    formantcorrection: int
    format: int
    fps: float
    frames: int
    freezecolor: Sequence[float]
    ft1: float
    fullspect: int
    gaincaption: int
    gaindragmode: int
    gainradius: float
    gainstyle: int
    genericeditor: int
    gensupport: int
    gfxengine: str
    ghostbar: int
    gizmos: int
    globalpatchername: str
    globalzoomfactor: int
    gradient: float
    graphcolor: Sequence[float]
    graphmode: str
    grid: Union[float, int]
    gridcolor: Sequence[float]
    gridlinecolor: Sequence[float]
    gridorigincolor: Sequence[float]
    gridstep_x: float
    gridstep_y: float
    hbgcolor: Sequence[float]
    hcellcolor: Sequence[float]
    hcurvecolor: Sequence[float]
    headercolor: Sequence[float]
    headerheight: int
    headerlabel: str
    hgraphcolor: Sequence[float]
    hidden: int
    hideloop: int
    hiderwff: int
    hilite: int
    hint: str
    hires: int
    hkeycolor: Sequence[float]
    hltcolor: Sequence[float]
    hlttextcolor: Sequence[float]
    horizontal_direction: int
    horizontalmargin: int
    horizontalspacing: int
    horizontaltracking: float
    hotcolor: Sequence[float]
    hscroll: int
    hsync: int
    htabcolor: Sequence[float]
    htextcolor: Sequence[float]
    htricolor: Sequence[float]
    idle: int
    idlemouse: int
    ignoreclick: int
    ignoreconnected: int
    ignoreemptyinterp: int
    illustrationspeed: int
    imagemask: int
    inactive: int
    inactivealpha: float
    inactivecoldcolor: Sequence[float]
    inactiveimage: int
    inactivelcdcolor: Sequence[float]
    inactivetextoffcolor: Sequence[float]
    inactivetextoncolor: Sequence[float]
    inactivewarmcolor: Sequence[float]
    inc: float
    includepackages: int
    incolormap: Atom
    increment: float
    index: int
    initial: Sequence[Atom]
    initialgain: float
    inlabels: Atom
    inputmode: int
    inputrangemode: int
    inputs: int
    inspectreadonly: int
    int: int
    interp: Union[float, int]
    interpinlet: int
    interval: Union[float, int]
    invert: int
    invisiblebkgnd: int
    items: Sequence[Any]
    jsarguments: Sequence[Atom]
    jump: int
    just: int
    justification: int
    jwebremotedebuggingport: int
    keymode: int
    keynavigate: int
    knobcolor: Sequence[float]
    knobpict: str
    knobshape: int
    knobsize: float
    labelclick: int
    labelheight: float
    labels: int
    labeltextcolor: Sequence[float]
    labelwidth: float
    lastchannelcount: int
    latency: Union[float, int]
    layoutbubbles: int
    lcdbgcolor: Sequence[float]
    lcdcolor: Sequence[float]
    leftarrow: int
    leftmargin: int
    leftvalue: int
    legacy: int
    legacyoutputorder: int
    legacytextcolor: int
    legacytransport: int
    legend: Union[int, str]
    linecolor: Sequence[float]
    linecount: int
    linenumbers: int
    linenumberwidth: int
    lines: int
    linethickness: float
    link: int
    linmarkers: Sequence[float]
    listmode: int
    listresize: int
    livemode: int
    loadbangonpaste: int
    local: int
    lock: int
    locked_bgcolor: Sequence[float]
    lockeddragscroll: int
    lockedsize: int
    logamp: int
    logfreq: int
    loglevel: int
    logmarkers: Sequence[float]
    logtosystemconsole: int
    loop: int
    loopbordercolor: Sequence[float]
    loopreport: int
    loopruler: int
    lsbfirst: int
    margin: int
    margins: Sequence[float]
    marker_horizontal: int
    marker_vertical: int
    markercolor: Sequence[float]
    markers: Sequence[int]
    markersused: int
    matrixmode: int
    maxdynamicnodes: int
    maxgain: float
    maximum: Atom
    maxurlproxyname: str
    maxwindow_dequeuesize: int
    maxwindow_fontname: str
    maxwindow_fontsize: int
    maxwindow_queuesize: int
    mcisolate: int
    mctrigchan: int
    menu_display: int
    menumode: int
    metering: int
    min: float
    minimum: Atom
    mode: Union[int, str]
    modulationcolor: Sequence[float]
    monitormode: int
    monochrome: int
    monotone: int
    mousefilter: int
    mousemode: int
    mousereport: int
    mouseup: int
    movehorizontal: int
    movevertical: int
    mult: float
    multiline: int
    multiplier: int
    multiselect: int
    multislider: int
    n4m_debug_log_enabled: int
    n4m_debug_log_folder: str
    n4m_debug_log_name: str
    n4m_external_node_binary: str
    n4m_process_manager_path: str
    name: str
    needlecolor: Sequence[float]
    needlemode: int
    neverdirty: int
    nfilters: int
    nhotleds: int
    nodecolor: Sequence[float]
    nodenumber: int
    nodesnames: Sequence[str]
    nofsaa: int
    noloadbangdefeating: int
    normalized: int
    norulerclick: int
    nosymquotes: int
    notebase: int
    notelist: Sequence[str]
    notename: int
    nseq: int
    nsize: Sequence[float]
    ntepidleds: int
    numdecimalplaces: int
    numdisplay: int
    numins: int
    numleds: int
    numouts: int
    numplots: int
    numpoints: int
    nwarmleds: int
    offcolor: Sequence[float]
    offset: Union[Sequence[float], float, int]
    oncolor: Sequence[float]
    onscreen: int
    orientation: int
    originallength: TimeValue
    originaltempo: float
    oscdefer: int
    oscparamenableddefault: int
    oscprefix: str
    oscprefixmode: int
    oscqueryenable: int
    oscqueryport: int
    oscreceivemode: int
    oscreceivequantize: TimeValue
    oscreceivethreshold: TimeValue
    oscreceiveudpport: int
    oscsendmode: int
    oscsendthreshold: TimeValue
    oscsendudpaddr: str
    oscsendudpport: int
    oscuseparamprefix: int
    oscvaluemode: int
    outcolormap: Atom
    outlabels: Atom
    outlettype: Any
    outlinecolor: Sequence[float]
    outmode: int
    output_texture: int
    outputalpha: int
    outputformat: str
    outputmode: int
    outputonclick: int
    outputs: int
    overdrive: int
    overgaincolor: Sequence[float]
    overloadcolor: Sequence[float]
    panelcolor: Sequence[float]
    param_connect: str
    parameter_enable: int
    parameter_mappable: int
    paramonly: int
    patcher: Any
    patcher_boxsnapmargin: Atom
    patcherinspector: int
    patchername: str
    patchingmargin: int
    patchingmarginpercent: float
    patchingmechanics: int
    patchline_curved: int
    patchlinecolor: Sequence[float]
    pattrmode: int
    pconstrain: int
    peakcolor: Sequence[float]
    permissive: int
    phasespect: int
    pic: str
    pickray: int
    pictures: Sequence[str]
    pitch_active: int
    pitchcorrection: int
    pitchdetection: int
    pitchshift: float
    pitchshiftcent: int
    planemap: Sequence[int]
    pointalign: float
    pointcolor: Sequence[float]
    pointsize: float
    polezerocolor: Sequence[float]
    poll: int
    popupbrowserbar: int
    precision: int
    prefer: str
    preffilename: str
    prefix: str
    prefix_mode: int
    presentation: int
    presentation_rect: Sequence[float]
    preservegain: int
    preset_data: Sequence[Any]
    preview: int
    prioritizeexterns: int
    prioritizepatchlines: int
    prototypename: str
    quality: str
    quiet: int
    range: Sequence[Atom]
    rangelabel: str
    ratio: int
    readonly: int
    realtime_params: int
    reflection: int
    reflectioncolor: Sequence[float]
    refreshrate: float
    relative: int
    release: Union[float, int]
    remapsvgcolors: int
    rendermode: int
    reportprogress: int
    restorewindows: int
    retune: int
    rightarrow: int
    rightmargin: int
    rightvalue: int
    rnbo_classname: str
    rnbo_extra_attributes: Dict[str, Any]
    rnbo_log_file: str
    rnbo_log_folder: str
    rnbo_log_level: int
    rnbo_server_autostart: int
    rounded: float
    rowhead: int
    rowheight: int
    rows: int
    running: int
    saturation: float
    saved_attribute_attributes: Dict[str, Any]
    saved_object_attributes: Dict[str, Any]
    savedependencies: int
    savemode: int
    savesingletons: int
    scale: Union[float, int]
    scaleknob: int
    sccolor: Sequence[float]
    scroll: int
    searchformissingfiles: int
    segmented: int
    segpatchcords: int
    selectalpha: float
    selectedclick: int
    selectioncolor: Sequence[float]
    selector: str
    selecttextonclick_patching: int
    selmode: int
    selsync: int
    separator: str
    setarrowkeysscrollpatcher: int
    seteventinterval: int
    setminmax: Sequence[float]
    setmixergbitmode: int
    setmixerlatency: float
    setmixerparallel: int
    setmixerramptime: float
    setmode: int
    setnativefontpanel: int
    setpollthrottle: int
    setqueuethrottle: int
    setresizes: int
    setscrollbarmode: int
    setslop: float
    setstyle: int
    setsysqelemthrottle: int
    settype: int
    setunit: int
    sgcolor: Sequence[float]
    shadow: int
    shadowactive: int
    shadowalpha: float
    shadowblend: float
    shadowline: int
    shadoworientation: int
    shadowperbar: int
    shadowproportion: float
    shadowreflectionpoint: float
    shadowsigned: int
    shape: int
    showcaption: int
    showcluebar: int
    showdotfiles: int
    showeditor: int
    showgain: int
    showgetonly: int
    showheader: int
    showlabels: int
    showname: int
    shownumber: int
    signalmode: str
    signalusecols: int
    signed: int
    sigoutmode: int
    size: float
    slidercolor: Sequence[float]
    slurtime: float
    smoothing: float
    snap: int
    snap2grid: int
    snapto: int
    snaptopixelbydefault: int
    sono: int
    sonohicolor: Sequence[float]
    sonolocolor: Sequence[float]
    sonomedcolor: Sequence[float]
    sonomedhicolor: Sequence[float]
    sonomedlocolor: Sequence[float]
    sonomonobgcolor: Sequence[float]
    sonomonofgcolor: Sequence[float]
    sortmode: int
    spacing: Union[float, int]
    spacing_x: float
    spacing_y: float
    srcrect: Sequence[int]
    staffs: int
    statusvisible: int
    stay: int
    stcolor: Sequence[float]
    stepcolor: Sequence[float]
    stepcolor2: Sequence[float]
    storage_rect: Sequence[float]
    stored1: Sequence[float]
    storeinpreset: int
    stripe2: Sequence[float]
    stripecolor: Sequence[float]
    style: str
    suppressinlet: int
    svg: str
    switchcolor: Sequence[float]
    sync: int
    syntax: str
    syntax_attrargcolor: Sequence[float]
    syntax_attributecolor: Sequence[float]
    syntax_objargcolor: Sequence[float]
    syntax_objectcolor: Sequence[float]
    syntaxcoloring: int
    syntaxcolorset: Atom
    systimerearlywake: int
    tabcolor: Sequence[float]
    table_data: Sequence[float]
    tabmode: int
    tabs: Sequence[str]
    tags: str
    template: str
    tepidcolor: Sequence[float]
    text: str
    text_width: float
    textcolor: Sequence[float]
    textcolor_inverse: Sequence[float]
    textjustification: int
    textoffcolor: Sequence[float]
    texton: str
    textoncolor: Sequence[float]
    textovercolor: Sequence[float]
    thickness: Union[float, int]
    thinmode: str
    thinthresh: int
    thinto: float
    threshold: float
    threshold_db: float
    threshold_linear: float
    ticks: int
    timestretch: int
    toggle: int
    tool: int
    toolbarcluemode: int
    toolbarquickrecord_format: int
    toolbarquickrecord_redbutton: int
    topmargin: int
    topvalue: int
    tosymbol: int
    trackcircular: int
    trackhorizontal: int
    tracking: int
    trackvertical: int
    transition: int
    translation: str
    triangle: int
    tribordercolor: Sequence[float]
    tricolor: Sequence[float]
    tricolor2: Sequence[float]
    trigger: int
    triglevel: float
    trioncolor: Sequence[float]
    triscale: float
    truncate: int
    types: Union[Atom, str]
    uncheckedcolor: Sequence[float]
    underline: int
    unitruler: int
    uparrow: int
    url: str
    use_16bit: int
    usebgoncolor: int
    usedstrect: int
    useexternaleditor: int
    useoffcolor: int
    usepicture: int
    usesearchpath: int
    useselectioncolor: int
    usespacesforjed: int
    usesrcrect: int
    usestepcolor2: int
    usesvgviewbox: int
    usetextovercolor: int
    usewebeditor: int
    valign: int
    valuemode: int
    valuepopup: int
    valuepopuplabel: int
    varname: str
    velocity_active: int
    vertical_direction: int
    verticalmargin: int
    verticalspacing: int
    verticaltracking: float
    videoengine: str
    viewvisibility: Any
    vlabels: int
    voffset: float
    vscroll: int
    vstscanmode: int
    vsync: int
    vticks: int
    vtracking: int
    vzoom: float
    warmcolor: Sequence[float]
    waveformcolor: Sequence[float]
    waveformdisplay: int
    wheelzoomdirection: int
    wheelzoomfactor: float
    whitekeycolor: Sequence[float]
    wiggletime: int
    wordwrap: int
    xoffset: float
    xplace: Sequence[float]
    yoffset: float
    yplace: Sequence[float]
    zoom_orientation: int
    zoomstyle: int
    zoomthresh: float


class TextboxProps(TypedDict, total=False):
    """As :class:`BoxProps`, minus the names the factory takes as parameters."""

    accentcolor: Sequence[float]
    accum: int
    accum_desat: float
    active: int
    active1: Sequence[float]
    activebgcolor: Sequence[float]
    activebgoncolor: Sequence[float]
    activecolor: Sequence[float]
    activedialcolor: Sequence[float]
    activefgdialcolor: Sequence[float]
    activeneedlecolor: Sequence[float]
    activesafe: int
    activeslidercolor: Sequence[float]
    activetextcolor: Sequence[float]
    activetextoncolor: Sequence[float]
    activetricolor: Sequence[float]
    activetricolor2: Sequence[float]
    addpoints: Sequence[Any]
    align: Atom
    allowdisabled: int
    allowdrag: int
    allowreorder: int
    allwindowsactive: int
    alpha: float
    amountcolor: Sequence[float]
    amxdtype: int
    annotation: str
    annotation_name: str
    appearance: int
    appicon_mac: str
    appicon_win: str
    applycolors: int
    applyfont: int
    arrow: int
    arrow_orientation: int
    arrowcolor: Sequence[float]
    arrows: int
    assistance: int
    attack: Union[float, int]
    attr: str
    attr_bpm: float
    attr_comment: str
    attr_display: int
    attrfilter: Sequence[str]
    audioframerate: float
    audioframesize: int
    auto_handle: int
    autoboxedit_patching: int
    autocompletionspace: int
    autoconnectusesmouseposition: int
    autoexport: int
    autofit: int
    autohint: int
    autolockunselected: int
    automatic: int
    automation: str
    automationon: str
    automouse: int
    autoout: int
    autopopulate: int
    autosave: int
    autoscroll: int
    autosize: int
    autosustain: int
    autowatch: int
    autowrite: int
    background: int
    bangmode: int
    basictuning: int
    bblend: int
    beats: int
    bgcolor: Sequence[float]
    bgcolor2: Sequence[float]
    bgfillcolor: Sequence[float]
    bgmode: int
    bgoncolor: Sequence[float]
    bgrulercolor: Sequence[float]
    bgstepcolor: Sequence[float]
    bgstepcolor2: Sequence[float]
    bgtransparent: int
    bgunitcolor: Sequence[float]
    bkgnddrag: int
    bkgndpict: str
    bkgndsize: int
    blackkeycolor: Sequence[float]
    blanksym: str
    blinkcolor: Sequence[float]
    blinktime: int
    border: int
    bordercolor: Sequence[float]
    bordercolor2: Sequence[float]
    bottommargin: int
    bottomvalue: int
    boundmode: int
    browsertext: str
    bubble: int
    bubble_bgcolor: Sequence[float]
    bubble_outlinecolor: Sequence[float]
    bubblepoint: float
    bubbleside: int
    bubblesize: int
    bubbletextmargin: int
    bubbleusescolors: int
    buffername: str
    bufsize: int
    bundleidentifier: str
    button: int
    bypass: int
    calccount: int
    candicane2: Sequence[float]
    candicane3: Sequence[float]
    candicane4: Sequence[float]
    candicane5: Sequence[float]
    candicane6: Sequence[float]
    candicane7: Sequence[float]
    candicane8: Sequence[float]
    candycane: int
    candycane2: Sequence[float]
    candycane3: Sequence[float]
    candycane4: Sequence[float]
    candycane5: Sequence[float]
    candycane6: Sequence[float]
    candycane7: Sequence[float]
    candycane8: Sequence[float]
    candymode: int
    cantchange: int
    cantclosetoplevelpatchers: int
    cefsupport: int
    cellheight: int
    cellpict: str
    cellwidth: int
    channelcount: int
    channels: int
    chanoffset: int
    chans: int
    checkedcolor: Sequence[float]
    checkforupdates: int
    classic_curve: int
    clearcolor: Sequence[float]
    clefs: int
    clickadd: int
    clickedimage: int
    clickinactive: int
    clickincrement: int
    clickmode: int
    clickmove: int
    clickmoveinactive: int
    clicksustain: int
    clickthrough: int
    client_rect: Sequence[float]
    clip: int
    clip_size: int
    clipdraw: int
    clipheight: float
    code: str
    coldcolor: Sequence[float]
    colhead: int
    collection: str
    color: Sequence[float]
    colorlabels: int
    colormode: str
    colorselectedtext: int
    colortheme: Atom
    colortitlebar: int
    cols: int
    columns: int
    colwidth: int
    compatibility: int
    connectacrossdividers: int
    constrainduplicates: int
    constrainpointchanges: int
    contdata: int
    contrast: float
    contrastactivetab: int
    convertobj: int
    cool: int
    coolcolor: Sequence[float]
    copysupport: int
    crashrecovery: str
    curvecolor: Sequence[float]
    data: Any
    database: int
    datadirty: int
    dbdisplay: int
    dbperled: int
    debugqueuesize: int
    decodemode: int
    default_template: str
    defaultcachesize: float
    defaultglcontext: str
    defaultm4ldevicesfolder: str
    defaultpatchersize: int
    defaultprojectsfolder: str
    defer: int
    degrees: int
    delay: Union[float, int]
    depth: Union[float, int]
    description: str
    devpath: str
    devpathtype: int
    dialcolor: Sequence[float]
    dialmode: int
    dialtracking: int
    digest: str
    dimmedconnectionalpha: float
    direction: int
    direction_height: float
    directioncolor: Sequence[float]
    dirty: int
    disabledalpha: float
    disabledcolor: Sequence[float]
    disablefind: int
    display_flat: int
    display_range: Sequence[float]
    displayamount: int
    displaychan: int
    displayknob: int
    displaymode: int
    displaysinglechannel: int
    dividercolor: Sequence[float]
    dividers: Atom
    dividersize: int
    domain: float
    domainlabel: str
    dontreplace: int
    downarrow: int
    drag_window: int
    dragtrack: int
    drawline: int
    drawoffcolor: int
    drawpeakhold: int
    drawpeaks: int
    drawstyle: int
    drawto: str
    dsp_cpulimit: str
    dsp_driver: int
    dsp_inputdevice: str
    dsp_iovectorsize: str
    dsp_option1: str
    dsp_option2: str
    dsp_outputdevice: str
    dsp_overdrive: str
    dsp_samplerate: str
    dsp_siai: str
    dsp_signalvectorsize: str
    dstrect: Sequence[int]
    duration_active: int
    dynamic: int
    editing_bgcolor: Sequence[float]
    editlocked: int
    editlooponly: int
    editor_rect: Sequence[float]
    elementcolor: Sequence[float]
    embed: int
    emptycolor: Sequence[float]
    enable: int
    enabled: int
    enablednotes: Sequence[Atom]
    enabledrag: int
    enableglobalcontext: int
    enablehscroll: int
    enablesprites: int
    enablevscroll: int
    erase_color: Sequence[float]
    exclusive: int
    expansion: str
    export_dpi: int
    exportfolder: str
    exportname: str
    exportnotifier: str
    exportscript: str
    exportscriptargs: str
    externaleditor: str
    extra1_active: int
    extra1_max: int
    extra1_min: int
    extra1_signed: int
    extra2_active: int
    extra2_max: int
    extra2_min: int
    extra2_signed: int
    extra_thickness: float
    factorycontent: int
    fblend: int
    fgcolor: Sequence[float]
    fgdialcolor: Sequence[float]
    file: str
    filekind: str
    filename: str
    fillhorizontalspace: int
    filternodeschanges: int
    filtertext: str
    flagmode: int
    floateditorwindow: int
    floatoutput: int
    focusbordercolor: Sequence[float]
    folderslash: int
    followglobaltempo: int
    followlivetheme: Atom
    fontface: int
    fontlink: int
    fontname: str
    fontsize: float
    forceaspect: int
    forcejwebrendermode: int
    formant: float
    formantcorrection: int
    format: int
    fps: float
    frames: int
    freezecolor: Sequence[float]
    ft1: float
    fullspect: int
    gaincaption: int
    gaindragmode: int
    gainradius: float
    gainstyle: int
    genericeditor: int
    gensupport: int
    gfxengine: str
    ghostbar: int
    gizmos: int
    globalpatchername: str
    globalzoomfactor: int
    gradient: float
    graphcolor: Sequence[float]
    graphmode: str
    grid: Union[float, int]
    gridcolor: Sequence[float]
    gridlinecolor: Sequence[float]
    gridorigincolor: Sequence[float]
    gridstep_x: float
    gridstep_y: float
    hbgcolor: Sequence[float]
    hcellcolor: Sequence[float]
    hcurvecolor: Sequence[float]
    headercolor: Sequence[float]
    headerheight: int
    headerlabel: str
    hgraphcolor: Sequence[float]
    hidden: int
    hideloop: int
    hiderwff: int
    hilite: int
    hint: str
    hires: int
    hkeycolor: Sequence[float]
    hltcolor: Sequence[float]
    hlttextcolor: Sequence[float]
    horizontal_direction: int
    horizontalmargin: int
    horizontalspacing: int
    horizontaltracking: float
    hotcolor: Sequence[float]
    hscroll: int
    hsync: int
    htabcolor: Sequence[float]
    htextcolor: Sequence[float]
    htricolor: Sequence[float]
    idle: int
    idlemouse: int
    ignoreclick: int
    ignoreconnected: int
    ignoreemptyinterp: int
    illustrationspeed: int
    imagemask: int
    inactive: int
    inactivealpha: float
    inactivecoldcolor: Sequence[float]
    inactiveimage: int
    inactivelcdcolor: Sequence[float]
    inactivetextoffcolor: Sequence[float]
    inactivetextoncolor: Sequence[float]
    inactivewarmcolor: Sequence[float]
    inc: float
    includepackages: int
    incolormap: Atom
    increment: float
    index: int
    initial: Sequence[Atom]
    initialgain: float
    inlabels: Atom
    inputmode: int
    inputrangemode: int
    inputs: int
    inspectreadonly: int
    int: int
    interp: Union[float, int]
    interpinlet: int
    interval: Union[float, int]
    invert: int
    invisiblebkgnd: int
    items: Sequence[Any]
    jsarguments: Sequence[Atom]
    jump: int
    just: int
    justification: int
    jwebremotedebuggingport: int
    keymode: int
    keynavigate: int
    knobcolor: Sequence[float]
    knobpict: str
    knobshape: int
    knobsize: float
    labelclick: int
    labelheight: float
    labels: int
    labeltextcolor: Sequence[float]
    labelwidth: float
    lastchannelcount: int
    latency: Union[float, int]
    layoutbubbles: int
    lcdbgcolor: Sequence[float]
    lcdcolor: Sequence[float]
    leftarrow: int
    leftmargin: int
    leftvalue: int
    legacy: int
    legacyoutputorder: int
    legacytextcolor: int
    legacytransport: int
    legend: Union[int, str]
    linecolor: Sequence[float]
    linecount: int
    linenumbers: int
    linenumberwidth: int
    lines: int
    linethickness: float
    link: int
    linmarkers: Sequence[float]
    listmode: int
    listresize: int
    livemode: int
    loadbangonpaste: int
    local: int
    lock: int
    locked_bgcolor: Sequence[float]
    lockeddragscroll: int
    lockedsize: int
    logamp: int
    logfreq: int
    loglevel: int
    logmarkers: Sequence[float]
    logtosystemconsole: int
    loop: int
    loopbordercolor: Sequence[float]
    loopreport: int
    loopruler: int
    lsbfirst: int
    margin: int
    margins: Sequence[float]
    marker_horizontal: int
    marker_vertical: int
    markercolor: Sequence[float]
    markers: Sequence[int]
    markersused: int
    matrixmode: int
    maxdynamicnodes: int
    maxgain: float
    maximum: Atom
    maxurlproxyname: str
    maxwindow_dequeuesize: int
    maxwindow_fontname: str
    maxwindow_fontsize: int
    maxwindow_queuesize: int
    mcisolate: int
    mctrigchan: int
    menu_display: int
    menumode: int
    metering: int
    min: float
    minimum: Atom
    mode: Union[int, str]
    modulationcolor: Sequence[float]
    monitormode: int
    monochrome: int
    monotone: int
    mousefilter: int
    mousemode: int
    mousereport: int
    mouseup: int
    movehorizontal: int
    movevertical: int
    mult: float
    multiline: int
    multiplier: int
    multiselect: int
    multislider: int
    n4m_debug_log_enabled: int
    n4m_debug_log_folder: str
    n4m_debug_log_name: str
    n4m_external_node_binary: str
    n4m_process_manager_path: str
    name: str
    needlecolor: Sequence[float]
    needlemode: int
    neverdirty: int
    nfilters: int
    nhotleds: int
    nodecolor: Sequence[float]
    nodenumber: int
    nodesnames: Sequence[str]
    nofsaa: int
    noloadbangdefeating: int
    normalized: int
    norulerclick: int
    nosymquotes: int
    notebase: int
    notelist: Sequence[str]
    notename: int
    nseq: int
    nsize: Sequence[float]
    ntepidleds: int
    numdecimalplaces: int
    numdisplay: int
    numins: int
    numleds: int
    numouts: int
    numplots: int
    numpoints: int
    nwarmleds: int
    offcolor: Sequence[float]
    offset: Union[Sequence[float], float, int]
    oncolor: Sequence[float]
    onscreen: int
    orientation: int
    originallength: TimeValue
    originaltempo: float
    oscdefer: int
    oscparamenableddefault: int
    oscprefix: str
    oscprefixmode: int
    oscqueryenable: int
    oscqueryport: int
    oscreceivemode: int
    oscreceivequantize: TimeValue
    oscreceivethreshold: TimeValue
    oscreceiveudpport: int
    oscsendmode: int
    oscsendthreshold: TimeValue
    oscsendudpaddr: str
    oscsendudpport: int
    oscuseparamprefix: int
    oscvaluemode: int
    outcolormap: Atom
    outlabels: Atom
    outlinecolor: Sequence[float]
    outmode: int
    output_texture: int
    outputalpha: int
    outputformat: str
    outputmode: int
    outputonclick: int
    outputs: int
    overdrive: int
    overgaincolor: Sequence[float]
    overloadcolor: Sequence[float]
    panelcolor: Sequence[float]
    param_connect: str
    parameter_enable: int
    parameter_mappable: int
    paramonly: int
    patcher: Any
    patcher_boxsnapmargin: Atom
    patcherinspector: int
    patchername: str
    patchingmargin: int
    patchingmarginpercent: float
    patchingmechanics: int
    patchline_curved: int
    patchlinecolor: Sequence[float]
    pattrmode: int
    pconstrain: int
    peakcolor: Sequence[float]
    permissive: int
    phasespect: int
    pic: str
    pickray: int
    pictures: Sequence[str]
    pitch_active: int
    pitchcorrection: int
    pitchdetection: int
    pitchshift: float
    pitchshiftcent: int
    planemap: Sequence[int]
    pointalign: float
    pointcolor: Sequence[float]
    pointsize: float
    polezerocolor: Sequence[float]
    poll: int
    popupbrowserbar: int
    precision: int
    prefer: str
    preffilename: str
    prefix: str
    prefix_mode: int
    presentation: int
    presentation_rect: Sequence[float]
    preservegain: int
    preset_data: Sequence[Any]
    preview: int
    prioritizeexterns: int
    prioritizepatchlines: int
    prototypename: str
    quality: str
    quiet: int
    range: Sequence[Atom]
    rangelabel: str
    ratio: int
    readonly: int
    realtime_params: int
    reflection: int
    reflectioncolor: Sequence[float]
    refreshrate: float
    relative: int
    release: Union[float, int]
    remapsvgcolors: int
    rendermode: int
    reportprogress: int
    restorewindows: int
    retune: int
    rightarrow: int
    rightmargin: int
    rightvalue: int
    rnbo_classname: str
    rnbo_extra_attributes: Dict[str, Any]
    rnbo_log_file: str
    rnbo_log_folder: str
    rnbo_log_level: int
    rnbo_server_autostart: int
    rounded: float
    rowhead: int
    rowheight: int
    rows: int
    running: int
    saturation: float
    saved_attribute_attributes: Dict[str, Any]
    saved_object_attributes: Dict[str, Any]
    savedependencies: int
    savemode: int
    savesingletons: int
    scale: Union[float, int]
    scaleknob: int
    sccolor: Sequence[float]
    scroll: int
    searchformissingfiles: int
    segmented: int
    segpatchcords: int
    selectalpha: float
    selectedclick: int
    selectioncolor: Sequence[float]
    selector: str
    selecttextonclick_patching: int
    selmode: int
    selsync: int
    separator: str
    setarrowkeysscrollpatcher: int
    seteventinterval: int
    setminmax: Sequence[float]
    setmixergbitmode: int
    setmixerlatency: float
    setmixerparallel: int
    setmixerramptime: float
    setmode: int
    setnativefontpanel: int
    setpollthrottle: int
    setqueuethrottle: int
    setresizes: int
    setscrollbarmode: int
    setslop: float
    setstyle: int
    setsysqelemthrottle: int
    settype: int
    setunit: int
    sgcolor: Sequence[float]
    shadow: int
    shadowactive: int
    shadowalpha: float
    shadowblend: float
    shadowline: int
    shadoworientation: int
    shadowperbar: int
    shadowproportion: float
    shadowreflectionpoint: float
    shadowsigned: int
    shape: int
    showcaption: int
    showcluebar: int
    showdotfiles: int
    showeditor: int
    showgain: int
    showgetonly: int
    showheader: int
    showlabels: int
    showname: int
    shownumber: int
    signalmode: str
    signalusecols: int
    signed: int
    sigoutmode: int
    size: float
    slidercolor: Sequence[float]
    slurtime: float
    smoothing: float
    snap: int
    snap2grid: int
    snapto: int
    snaptopixelbydefault: int
    sono: int
    sonohicolor: Sequence[float]
    sonolocolor: Sequence[float]
    sonomedcolor: Sequence[float]
    sonomedhicolor: Sequence[float]
    sonomedlocolor: Sequence[float]
    sonomonobgcolor: Sequence[float]
    sonomonofgcolor: Sequence[float]
    sortmode: int
    spacing: Union[float, int]
    spacing_x: float
    spacing_y: float
    srcrect: Sequence[int]
    staffs: int
    statusvisible: int
    stay: int
    stcolor: Sequence[float]
    stepcolor: Sequence[float]
    stepcolor2: Sequence[float]
    storage_rect: Sequence[float]
    stored1: Sequence[float]
    storeinpreset: int
    stripe2: Sequence[float]
    stripecolor: Sequence[float]
    style: str
    suppressinlet: int
    svg: str
    switchcolor: Sequence[float]
    sync: int
    syntax: str
    syntax_attrargcolor: Sequence[float]
    syntax_attributecolor: Sequence[float]
    syntax_objargcolor: Sequence[float]
    syntax_objectcolor: Sequence[float]
    syntaxcoloring: int
    syntaxcolorset: Atom
    systimerearlywake: int
    tabcolor: Sequence[float]
    table_data: Sequence[float]
    tabmode: int
    tabs: Sequence[str]
    tags: str
    template: str
    tepidcolor: Sequence[float]
    text_width: float
    textcolor: Sequence[float]
    textcolor_inverse: Sequence[float]
    textjustification: int
    textoffcolor: Sequence[float]
    texton: str
    textoncolor: Sequence[float]
    textovercolor: Sequence[float]
    thickness: Union[float, int]
    thinmode: str
    thinthresh: int
    thinto: float
    threshold: float
    threshold_db: float
    threshold_linear: float
    ticks: int
    timestretch: int
    toggle: int
    tool: int
    toolbarcluemode: int
    toolbarquickrecord_format: int
    toolbarquickrecord_redbutton: int
    topmargin: int
    topvalue: int
    tosymbol: int
    trackcircular: int
    trackhorizontal: int
    tracking: int
    trackvertical: int
    transition: int
    translation: str
    triangle: int
    tribordercolor: Sequence[float]
    tricolor: Sequence[float]
    tricolor2: Sequence[float]
    trigger: int
    triglevel: float
    trioncolor: Sequence[float]
    triscale: float
    truncate: int
    types: Union[Atom, str]
    uncheckedcolor: Sequence[float]
    underline: int
    unitruler: int
    uparrow: int
    url: str
    use_16bit: int
    usebgoncolor: int
    usedstrect: int
    useexternaleditor: int
    useoffcolor: int
    usepicture: int
    usesearchpath: int
    useselectioncolor: int
    usespacesforjed: int
    usesrcrect: int
    usestepcolor2: int
    usesvgviewbox: int
    usetextovercolor: int
    usewebeditor: int
    valign: int
    valuemode: int
    valuepopup: int
    valuepopuplabel: int
    varname: str
    velocity_active: int
    vertical_direction: int
    verticalmargin: int
    verticalspacing: int
    verticaltracking: float
    videoengine: str
    viewvisibility: Any
    vlabels: int
    voffset: float
    vscroll: int
    vstscanmode: int
    vsync: int
    vticks: int
    vtracking: int
    vzoom: float
    warmcolor: Sequence[float]
    waveformcolor: Sequence[float]
    waveformdisplay: int
    wheelzoomdirection: int
    wheelzoomfactor: float
    whitekeycolor: Sequence[float]
    wiggletime: int
    wordwrap: int
    xoffset: float
    xplace: Sequence[float]
    yoffset: float
    yplace: Sequence[float]
    zoom_orientation: int
    zoomstyle: int
    zoomthresh: float


#: Every property name in :class:`BoxProps`, for runtime checks.
BOX_PROP_NAMES = frozenset(BoxProps.__annotations__)
