#!/usr/bin/env python3
"""Generate the js2max verification patches under ``js2max/max/``.

Two, because they answer different questions:

``v8-harness.maxpat``
    Every message, run against the patch itself. Serializing it produces
    something resembling it -- a fair round-trip check, but you cannot tell a
    real serialization from a file copy by looking at it.

``save-demo.maxpat``
    The exact route out: ``save`` (the message) and ``writePatch`` (the library
    call, via ``save-example.js``). A description is written straight to disk
    and no objects are created.

``serialize-demo.maxpat``
    Reading a live patcher back as *data*. Saving the result is a worse ``cp``,
    so the demo filters instead: ``extract`` pulls the signal chain out of a
    mixed patch and writes it as its own file, which no copy could produce.
    ``serialize-example.js`` adds two more things data allows and a copy does
    not -- reporting what is unconnected, and rewriting the layout in place.

The TypeScript bridge is unit-tested against a mock host, which proves the
mapping from a patch description to `newdefault`/`connect` calls. It cannot
prove that Max accepts those calls; only Max can. This generates the patch you
open to find out.

Generated by py2max rather than written by hand, which is the point: the Python
package emits the patch, the patch loads the TypeScript bundle, and the bundle
builds objects from the same format the Python package writes. Both ends of the
loop come from one description of the format.

Usage:
    python scripts/gen_v8_harness.py            # write the harness
    python scripts/gen_v8_harness.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from py2max import Patcher  # noqa: E402
from py2max.core.common import Rect  # noqa: E402

OUT_DIR = ROOT / "js2max" / "max"
HARNESS = OUT_DIR / "v8-harness.maxpat"
SAVE_DEMO = OUT_DIR / "save-demo.maxpat"
SERIALIZE_DEMO = OUT_DIR / "serialize-demo.maxpat"

# The bundle sits beside this patch, so `v8` finds it without a search path
# entry. Keep the two in the same directory.
BUNDLE = "js2max.v8.js"


def build(path: Path) -> Patcher:
    # Taller than the default 480 so the objects `demo` builds, which land
    # below this patch's own controls, are on screen without scrolling.
    p = Patcher(str(path))
    p.rect = Rect(85.0, 104.0, 640.0, 620.0)

    p.add_comment(
        "js2max -- v8 verification harness",
        patching_rect=Rect(24, 20, 460, 24),
        fontsize=14.0,
    )
    p.add_comment(
        "Click a message. Objects are built into THIS patcher, in the empty "
        "space to the right. 'clear' undoes the last build; 'clearall' empties "
        "the patcher apart from the [v8] object itself.",
        patching_rect=Rect(24, 44, 460, 48),
    )

    demo = p.add_message("demo", patching_rect=Rect(24, 108, 48, 22))
    count = p.add_message("count", patching_rect=Rect(84, 108, 52, 22))
    clear = p.add_message("clear", patching_rect=Rect(148, 108, 48, 22))
    clearall = p.add_message("clearall", patching_rect=Rect(208, 108, 66, 22))

    # `read`/`write` need a path; edit the placeholder before clicking.
    read = p.add_message(
        "read my-patch.maxpat", patching_rect=Rect(24, 140, 168, 22)
    )
    # A relative name, which Max resolves next to this patch -- confirmed by
    # running it. The output lands in js2max/max/ and is gitignored.
    write = p.add_message(
        "write js2max-write-test.maxpat",
        patching_rect=Rect(200, 140, 200, 22),
    )
    probe = p.add_message("probe", patching_rect=Rect(408, 140, 50, 22))

    # The assumptions the rest of the bridge rests on. `verify` builds what each
    # check needs, observes what Max does, and removes it again -- so it is safe
    # to click on any patch, and one click settles all four.
    verify = p.add_message("verify", patching_rect=Rect(24, 172, 56, 22))

    # The follow-up to a `verify` failure: where `verify` says whether an
    # assumption held, `diagnose` builds the variants side by side and prints
    # every field, so a fix can be written from evidence. Expect Max to log
    # `No such object` -- that is the experiment, not a fault.
    diagnose = p.add_message("diagnose", patching_rect=Rect(88, 172, 68, 22))

    # The usable form of `build`, as a three-click chain that needs nothing
    # from outside this patch. `save` writes the built-in synth description to
    # a file -- 9 boxes, no [v8] object, so what gets built is unmistakably not
    # a copy of this patch. `import_json` loads that file into the dict, and
    # `builddict` tells js2max to build what the dict holds.
    #
    # Deliberately not `write`'s output: that is this whole patcher serialized,
    # [v8] box included, so building it would drop a second copy of the script
    # into the patch.
    # `import`, not `import_json` -- the latter does not exist, and `dict`
    # answers `doesn't understand "import_json"`. Confirmed against the dict
    # reference: `import` reads a dictionary's contents from a .json or .yaml
    # file, `export` writes one.
    #
    # The file is `.json` rather than `.maxpat` for the same reason: `import`
    # chooses its reader by extension, and a `.maxpat` is JSON by content but
    # not by name. `save` writes whatever path it is given, so the extension
    # costs nothing.
    save_dict = p.add_message(
        "save js2max-dict-test.json", patching_rect=Rect(164, 172, 190, 22)
    )
    load_dict = p.add_message(
        "import js2max-dict-test.json",
        patching_rect=Rect(164, 204, 190, 22),
    )
    patch_dict = p.add_textbox(
        "dict js2max_patch",
        patching_rect=Rect(164, 236, 120, 22),
        numinlets=2,
        numoutlets=4,
        outlettype=["dictionary", "", "", ""],
    )
    build_dict = p.add_message(
        "builddict js2max_patch", patching_rect=Rect(300, 236, 150, 22)
    )

    v8 = p.add_textbox(
        f"v8 {BUNDLE}",
        patching_rect=Rect(24, 244, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )
    printer = p.add_textbox(
        "print js2max",
        patching_rect=Rect(24, 292, 90, 22),
        numinlets=1,
        numoutlets=0,
    )

    sources = (
        demo, count, clear, clearall, read, write, probe, verify, diagnose,
        save_dict, build_dict,
    )
    for source in sources:
        p.add_line(source, v8)
    p.add_line(load_dict, patch_dict)
    p.add_line(v8, printer)

    p.add_comment(
        "Expected on 'demo': three objects appear (cycle~ 440 -> gain~ -> "
        "ezdac~) and the Max window logs 'created 3 object(s), 3 connection(s)'. "
        "'clear' then removes exactly those three, leaving this patch intact. "
        "'read' opens a .maxpat and builds it. 'write' serializes THIS WHOLE "
        "patcher -- these boxes and the [v8] object included -- so its output "
        "resembles this patch by design; it is a round-trip check, not an "
        "export of just what you built. It refuses to write over this patch's "
        "own file. 'probe' logs what each box reports about itself.",
        patching_rect=Rect(24, 328, 460, 90),
    )
    p.add_comment(
        "'verify' is the one to click first. It settles the four assumptions "
        "everything else rests on -- whether 'set' fills a message box, whether "
        "newdefault returns null or throws for an unknown class, whether a "
        "subpatcher box exposes its patcher, and whether snapshot reads a live "
        "one -- by doing each in turn and reading back what Max did. It builds "
        "what it needs and removes it again, so the patcher is left as found. "
        "Any line logged '[NO ]' is a real finding: copy the console output. "
        "'diagnose' is the follow-up: it builds the variants side by side and "
        "prints every field, which is what a fix gets written from. "
        "The dict chain is the usable form of 'build', in three clicks: "
        "'save' writes the built-in synth to a .json file, 'import' loads that "
        "file into the [dict], and 'builddict' builds what the dict holds. A "
        "message box ends its message at the first comma, so a .maxpat cannot "
        "be sent as a message at all; a dict is passed by name instead. "
        "'clear' removes what was built.",
        patching_rect=Rect(24, 422, 460, 114),
    )
    return p


def build_save_demo(path: Path) -> Patcher:
    """`save` and `writePatch`: a description written straight to disk."""
    p = Patcher(str(path))
    p.rect = Rect(85.0, 104.0, 580.0, 470.0)

    p.add_comment(
        "js2max -- save / writePatch",
        patching_rect=Rect(24, 20, 460, 24),
        fontsize=14.0,
    )
    p.add_comment(
        "The exact route out. A description is already the shape of a .maxpat, "
        "so writing it needs no accessor, no default to guess at and no live "
        "patcher -- nothing is created here, and nothing is lost. This is the "
        "normal way to write a patch from code.",
        patching_rect=Rect(24, 44, 500, 62),
    )

    p.add_comment(
        "As a message, to the shipped script:",
        patching_rect=Rect(24, 116, 300, 20),
    )
    save = p.add_message(
        "save js2max-demo-out.maxpat", patching_rect=Rect(24, 138, 200, 22)
    )
    v8 = p.add_textbox(
        f"v8 {BUNDLE}",
        patching_rect=Rect(24, 174, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    p.add_comment(
        "Or from your own script -- open save-example.js to read it:",
        patching_rect=Rect(24, 218, 400, 20),
    )
    go = p.add_message("bang", patching_rect=Rect(24, 240, 42, 22))
    verify = p.add_message("verify", patching_rect=Rect(76, 240, 52, 22))
    example = p.add_textbox(
        "v8 save-example.js",
        patching_rect=Rect(24, 276, 180, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    printer = p.add_textbox(
        "print js2max",
        patching_rect=Rect(24, 320, 90, 22),
        numinlets=1,
        numoutlets=0,
    )

    p.add_line(save, v8)
    p.add_line(v8, printer)
    for source in (go, verify):
        p.add_line(source, example)
    p.add_line(example, printer)
    return p


def build_serialize_demo(path: Path) -> Patcher:
    """`write` and `serialize`: a live patcher read back as data, then filtered."""
    p = Patcher(str(path))
    p.rect = Rect(85.0, 104.0, 640.0, 600.0)

    p.add_comment(
        "js2max -- write / serialize",
        patching_rect=Rect(24, 20, 460, 24),
        fontsize=14.0,
    )
    p.add_comment(
        "Serializing a whole patcher and saving it is a worse 'cp' -- a file "
        "copy is exact and this is not. The point is getting the patch as DATA. "
        "Once you have that you can filter it, measure it or rewrite it, and "
        "end up with something no copy could produce.",
        patching_rect=Rect(24, 44, 560, 62),
    )

    # A mixed patch: control objects and a signal chain, so there is something
    # to separate. Placed here by hand, not built by script -- which is the
    # situation reading a live patcher is actually for.
    tog = p.add_textbox("toggle", patching_rect=Rect(380, 150, 24, 24))
    metro = p.add_textbox("metro 500", patching_rect=Rect(380, 186, 76, 22))
    rand = p.add_textbox("random 24", patching_rect=Rect(380, 222, 76, 22))
    plus = p.add_textbox("+ 48", patching_rect=Rect(380, 258, 48, 22))
    tomf = p.add_textbox("mtof", patching_rect=Rect(380, 294, 45, 22))
    osc = p.add_textbox("cycle~", patching_rect=Rect(380, 330, 60, 22))
    amp = p.add_textbox("*~ 0.15", patching_rect=Rect(380, 366, 62, 22))
    dac = p.add_textbox("ezdac~", patching_rect=Rect(380, 402, 45, 45))

    p.add_line(tog, metro)
    p.add_line(metro, rand)
    p.add_line(rand, plus)
    p.add_line(plus, tomf)
    p.add_line(tomf, osc)
    p.add_line(osc, amp)
    p.add_line(amp, dac, inlet=0)
    p.add_line(amp, dac, inlet=1)

    p.add_comment(
        "Five control objects and three signal ones, mixed. 'extract' pulls "
        "out just the signal chain.",
        patching_rect=Rect(380, 460, 220, 48),
    )

    p.add_comment(
        "As a message, to the shipped script:",
        patching_rect=Rect(24, 118, 320, 20),
    )
    extract = p.add_message(
        "extract js2max-signal-chain.maxpat", patching_rect=Rect(24, 140, 230, 22)
    )
    write = p.add_message(
        "write js2max-whole-patcher.maxpat", patching_rect=Rect(24, 176, 225, 22)
    )
    p.add_comment(
        "^ the pointless one: a lossy copy of this file. Kept so you can "
        "compare it with the extraction above.",
        patching_rect=Rect(24, 202, 320, 34),
    )
    v8 = p.add_textbox(
        f"v8 {BUNDLE}",
        patching_rect=Rect(24, 244, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    p.add_comment(
        "Or from your own script -- open serialize-example.js:",
        patching_rect=Rect(24, 288, 400, 20),
    )
    go = p.add_message("bang", patching_rect=Rect(24, 310, 42, 22))
    report = p.add_message("report", patching_rect=Rect(76, 310, 56, 22))
    tidy = p.add_message("spread", patching_rect=Rect(142, 310, 56, 22))
    example = p.add_textbox(
        "v8 serialize-example.js",
        patching_rect=Rect(24, 346, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    printer = p.add_textbox(
        "print js2max",
        patching_rect=Rect(24, 390, 90, 22),
        numinlets=1,
        numoutlets=0,
    )

    for source in (extract, write):
        p.add_line(source, v8)
    p.add_line(v8, printer)
    for source in (go, report, tidy):
        p.add_line(source, example)
    p.add_line(example, printer)
    return p


def render(path: Path) -> str:
    return build(path).to_json()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if either patch is stale"
    )
    args = parser.parse_args()

    patches = [
        (HARNESS, build(HARNESS).to_json()),
        (SAVE_DEMO, build_save_demo(SAVE_DEMO).to_json()),
        (SERIALIZE_DEMO, build_serialize_demo(SERIALIZE_DEMO).to_json()),
    ]

    if args.check:
        stale = False
        for path, fresh in patches:
            if not path.exists():
                print(f"{path} is missing; run: python scripts/gen_v8_harness.py")
                stale = True
            # Compare parsed, not textual: json formatting is not the contract.
            elif json.loads(path.read_text()) != json.loads(fresh):
                print(f"{path} is stale; run: python scripts/gen_v8_harness.py")
                stale = True
            else:
                print(f"{path} is up to date")
        return 1 if stale else 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, fresh in patches:
        path.write_text(fresh)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
