#!/usr/bin/env python3
"""Generate the js2max verification patches under ``js2max/max/``.

Two, because they answer different questions:

``v8-harness.maxpat``
    Every message, run against the patch itself. Serializing it produces
    something resembling it -- a fair round-trip check, but you cannot tell a
    real serialization from a file copy by looking at it.

``save-demo.maxpat``
    The exact route out: ``save`` (the message) and ``writePatch`` (the library
    call, via ``save-example.js``). A description is written straight to disk
    and no objects are created.

``serialize-demo.maxpat``
    The lossy route out, for when the objects in a patcher are the source of
    truth: ``write`` (the message) and ``serialize`` (the library call, via
    ``serialize-example.js``). The patch contains a small instrument placed by
    hand, which is what gets captured.

The TypeScript bridge is unit-tested against a mock host, which proves the
mapping from a patch description to `newdefault`/`connect` calls. It cannot
prove that Max accepts those calls; only Max can. This generates the patch you
open to find out.

Generated by py2max rather than written by hand, which is the point: the Python
package emits the patch, the patch loads the TypeScript bundle, and the bundle
builds objects from the same format the Python package writes. Both ends of the
loop come from one description of the format.

Usage:
    python scripts/gen_v8_harness.py            # write the harness
    python scripts/gen_v8_harness.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from py2max import Patcher  # noqa: E402
from py2max.core.common import Rect  # noqa: E402

OUT_DIR = ROOT / "js2max" / "max"
HARNESS = OUT_DIR / "v8-harness.maxpat"
SAVE_DEMO = OUT_DIR / "save-demo.maxpat"
SERIALIZE_DEMO = OUT_DIR / "serialize-demo.maxpat"

# The bundle sits beside this patch, so `v8` finds it without a search path
# entry. Keep the two in the same directory.
BUNDLE = "js2max.v8.js"


def build(path: Path) -> Patcher:
    # Taller than the default 480 so the objects `demo` builds, which land
    # below this patch's own controls, are on screen without scrolling.
    p = Patcher(str(path))
    p.rect = Rect(85.0, 104.0, 640.0, 560.0)

    p.add_comment(
        "js2max -- v8 verification harness",
        patching_rect=Rect(24, 20, 460, 24),
        fontsize=14.0,
    )
    p.add_comment(
        "Click a message. Objects are built into THIS patcher, in the empty "
        "space to the right. 'clear' undoes the last build; 'clearall' empties "
        "the patcher apart from the [v8] object itself.",
        patching_rect=Rect(24, 44, 460, 48),
    )

    demo = p.add_message("demo", patching_rect=Rect(24, 108, 48, 22))
    count = p.add_message("count", patching_rect=Rect(84, 108, 52, 22))
    clear = p.add_message("clear", patching_rect=Rect(148, 108, 48, 22))
    clearall = p.add_message("clearall", patching_rect=Rect(208, 108, 66, 22))

    # `read`/`write` need a path; edit the placeholder before clicking.
    read = p.add_message(
        "read my-patch.maxpat", patching_rect=Rect(24, 140, 168, 22)
    )
    # A relative name, which Max resolves next to this patch -- confirmed by
    # running it. The output lands in js2max/max/ and is gitignored.
    write = p.add_message(
        "write js2max-write-test.maxpat",
        patching_rect=Rect(200, 140, 200, 22),
    )
    probe = p.add_message("probe", patching_rect=Rect(408, 140, 50, 22))


    v8 = p.add_textbox(
        f"v8 {BUNDLE}",
        patching_rect=Rect(24, 180, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )
    printer = p.add_textbox(
        "print js2max",
        patching_rect=Rect(24, 228, 90, 22),
        numinlets=1,
        numoutlets=0,
    )

    for source in (demo, count, clear, clearall, read, write, probe):
        p.add_line(source, v8)
    p.add_line(v8, printer)

    p.add_comment(
        "Expected on 'demo': three objects appear (cycle~ 440 -> gain~ -> "
        "ezdac~) and the Max window logs 'created 3 object(s), 3 connection(s)'. "
        "'clear' then removes exactly those three, leaving this patch intact. "
        "'read' opens a .maxpat and builds it. 'write' serializes THIS WHOLE "
        "patcher -- these boxes and the [v8] object included -- so its output "
        "resembles this patch by design; it is a round-trip check, not an "
        "export of just what you built. It refuses to write over this patch's "
        "own file. 'probe' logs what each box reports about itself.",
        patching_rect=Rect(24, 264, 460, 90),
    )
    return p


def build_save_demo(path: Path) -> Patcher:
    """`save` and `writePatch`: a description written straight to disk."""
    p = Patcher(str(path))
    p.rect = Rect(85.0, 104.0, 580.0, 470.0)

    p.add_comment(
        "js2max -- save / writePatch",
        patching_rect=Rect(24, 20, 460, 24),
        fontsize=14.0,
    )
    p.add_comment(
        "The exact route out. A description is already the shape of a .maxpat, "
        "so writing it needs no accessor, no default to guess at and no live "
        "patcher -- nothing is created here, and nothing is lost. This is the "
        "normal way to write a patch from code.",
        patching_rect=Rect(24, 44, 500, 62),
    )

    p.add_comment(
        "As a message, to the shipped script:",
        patching_rect=Rect(24, 116, 300, 20),
    )
    save = p.add_message(
        "save js2max-demo-out.maxpat", patching_rect=Rect(24, 138, 200, 22)
    )
    v8 = p.add_textbox(
        f"v8 {BUNDLE}",
        patching_rect=Rect(24, 174, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    p.add_comment(
        "Or from your own script -- open save-example.js to read it:",
        patching_rect=Rect(24, 218, 400, 20),
    )
    go = p.add_message("bang", patching_rect=Rect(24, 240, 42, 22))
    verify = p.add_message("verify", patching_rect=Rect(76, 240, 52, 22))
    example = p.add_textbox(
        "v8 save-example.js",
        patching_rect=Rect(24, 276, 180, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    printer = p.add_textbox(
        "print js2max",
        patching_rect=Rect(24, 320, 90, 22),
        numinlets=1,
        numoutlets=0,
    )

    p.add_line(save, v8)
    p.add_line(v8, printer)
    for source in (go, verify):
        p.add_line(source, example)
    p.add_line(example, printer)
    return p


def build_serialize_demo(path: Path) -> Patcher:
    """`write` and `serialize`: a live patcher read back out."""
    p = Patcher(str(path))
    p.rect = Rect(85.0, 104.0, 580.0, 560.0)

    p.add_comment(
        "js2max -- write / serialize",
        patching_rect=Rect(24, 20, 460, 24),
        fontsize=14.0,
    )
    p.add_comment(
        "The lossy route out, for when the objects ARE the source of truth -- "
        "someone placed them by hand. Every field has to be rebuilt from what "
        "the JS API exposes, so a font equal to the patcher default cannot be "
        "told from an unset one, port counts maxref does not state are omitted, "
        "and linecount / filename / textfile have no accessor at all. Prefer "
        "save when you are exporting something you described in code.",
        patching_rect=Rect(24, 44, 500, 90),
    )

    # Something worth capturing: a small chain placed here, not built by script.
    osc = p.add_textbox("cycle~ 330", patching_rect=Rect(320, 150, 76, 22))
    amp = p.add_textbox("*~ 0.15", patching_rect=Rect(320, 186, 62, 22))
    dac = p.add_textbox("ezdac~", patching_rect=Rect(320, 222, 45, 45))
    p.add_line(osc, amp)
    p.add_line(amp, dac, inlet=0)
    p.add_line(amp, dac, inlet=1)
    p.add_comment(
        "<- this is what gets captured",
        patching_rect=Rect(320, 276, 200, 20),
    )

    p.add_comment(
        "As a message, to the shipped script:",
        patching_rect=Rect(24, 146, 300, 20),
    )
    write = p.add_message(
        "write js2max-live-out.maxpat", patching_rect=Rect(24, 168, 210, 22)
    )
    v8 = p.add_textbox(
        f"v8 {BUNDLE}",
        patching_rect=Rect(24, 204, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    p.add_comment(
        "Or from your own script -- open serialize-example.js:",
        patching_rect=Rect(24, 248, 400, 20),
    )
    go = p.add_message("bang", patching_rect=Rect(24, 270, 42, 22))
    inspect = p.add_message("inspect", patching_rect=Rect(76, 270, 58, 22))
    example = p.add_textbox(
        "v8 serialize-example.js",
        patching_rect=Rect(24, 306, 200, 22),
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
    )

    printer = p.add_textbox(
        "print js2max",
        patching_rect=Rect(24, 350, 90, 22),
        numinlets=1,
        numoutlets=0,
    )

    p.add_line(write, v8)
    p.add_line(v8, printer)
    for source in (go, inspect):
        p.add_line(source, example)
    p.add_line(example, printer)
    return p


def render(path: Path) -> str:
    return build(path).to_json()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if either patch is stale"
    )
    args = parser.parse_args()

    patches = [
        (HARNESS, build(HARNESS).to_json()),
        (SAVE_DEMO, build_save_demo(SAVE_DEMO).to_json()),
        (SERIALIZE_DEMO, build_serialize_demo(SERIALIZE_DEMO).to_json()),
    ]

    if args.check:
        stale = False
        for path, fresh in patches:
            if not path.exists():
                print(f"{path} is missing; run: python scripts/gen_v8_harness.py")
                stale = True
            # Compare parsed, not textual: json formatting is not the contract.
            elif json.loads(path.read_text()) != json.loads(fresh):
                print(f"{path} is stale; run: python scripts/gen_v8_harness.py")
                stale = True
            else:
                print(f"{path} is up to date")
        return 1 if stale else 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, fresh in patches:
        path.write_text(fresh)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
