descriptions = {
 0: 'A collection of messages to send remotely',
 1: 'A matrix-friendly MSP buffer~',
 2: 'A set of matrices for storage/resequencing',
 3: 'ADSR envelope generator for signals',
 4: 'AIFF saving and playing',
 5: 'ASCII number for each character in a string',
 6: 'ASCII number, convert to text character',
 7: 'ASCII numbers, convert symbol to',
 8: 'Absolute to relative path conversion',
 9: 'Absolute value',
 10: 'Accelerate Max timing in objects',
 11: 'Accelerate, control clock speed of Max timing objects',
 12: 'Access all pattr objects in a patcher',
 13: 'Access audio driver output channels',
 14: 'Accumulator',
 15: 'Active sensing, MIDI system message',
 16: 'Add',
 17: 'Additive synthesis',
 18: 'Address elements in an array by index number',
 19: 'Adjust image brightness/contrast/saturation',
 20: 'Afterpressure, polyphonic',
 21: 'Aftertouch (monophonic) MIDI message',
 22: 'Alert',
 23: 'Aliasing',
 24: 'All notes off (MIDI Mode message)',
 25: 'Allocate notes to different voices',
 26: 'Allpass filter',
 27: 'Amplitude',
 28: 'Analog-to-digital converter',
 29: 'Analysis of a signal',
 30: 'Analyze a signal',
 31: 'Analyzing video',
 32: 'And, true if both statements are true (logical intersection)',
 33: 'Animation of shapes or pictures',
 34: 'Animation, control a laser videodisc player',
 35: 'Animation, play a QuickTime movie',
 36: 'Antialiased oscillators',
 37: 'Append or prepend text to a message',
 38: 'Apply binary or unary operators',
 39: 'Apply common string operations',
 40: 'Apply single force to particles',
 41: 'Arbitrary rectangular resampling',
 42: 'Arc- functions for numbers, matrices and signals',
 43: 'Arithmetic operators',
 44: 'Array of arbitrary messages',
 45: 'Array of numbers',
 46: 'Ascii to integers',
 47: 'Ask',
 48: 'Assign one of several inputs to an outlet',
 49: 'Assistance, attach an assistance message to an inlet or outlet in a '
     'subpatch',
 50: 'Atoms of a list, break up into individual messages',
 51: 'Audio driver settings, reporting and controlling',
 52: 'Audio I/O',
 53: 'Audio processing system utilities',
 54: 'Average a running stream of numbers',
 55: 'Background colour',
 56: 'Background panel',
 57: 'Background, notify objects when patcher window is moved to background',
 58: 'Backward sample playback',
 59: 'Band-limited random signal',
 60: 'Bandpass filter',
 61: 'the bang message',
 62: 'Binary, display numbers as',
 63: 'Bit shifting',
 64: 'Bitwise ones complement operation',
 65: 'Bitwise operators',
 66: 'Boolean logic operations',
 67: 'Break up a list',
 68: 'Breakpoint line segment function generation and storage',
 69: 'Breath control',
 70: 'Broadcast a message to all instances of the same class in a patcher',
 71: 'Broadcast video using RTSP (Macintosh only)',
 72: 'Brownian motion simulator',
 73: 'Bubble sort',
 74: 'Buffer-based audio',
 75: 'Buffer-based FIR filter',
 76: 'Buffer viewer and editor',
 77: 'Build',
 78: 'Button for user Interface',
 79: 'Bypassing a signal',
 80: 'C language expression solving',
 81: 'Calculate',
 82: 'Capture and display a series of numbers',
 83: 'Cartesian to Polar coordinate conversion',
 84: 'Cascaded series of biquad filters',
 85: 'Cellwise envelope follower for matrices',
 86: 'Chance operations using pseudo-random numbers',
 87: 'Change background colour',
 88: 'Characters in a string of text, convert to ASCII numbers',
 89: 'Check box user interface object',
 90: 'Choke chromakey 3 sources',
 91: 'Chorusing',
 92: 'Clipping',
 93: 'Clock for reporting time elapsed',
 94: 'Clock speed of Max timing objects, control',
 95: 'Clock, MIDI system message',
 96: 'Close a patcher window automatically',
 97: 'Closing a patcher window, send a bang when window is closed',
 98: 'Coerce a matrix into different types/planecount',
 99: 'Collect',
 100: 'Collection of messages, store and recall',
 101: 'Color screen with threshold',
 102: 'Color selection using a modal dialog',
 103: 'Color swatch for RGB color selection and display',
 104: 'Colored button area',
 105: 'Comb filter with feedforward and feedback delay control',
 106: 'Comb filter',
 107: 'Combinatorics, produce random orderings of a set',
 108: 'Combine',
 109: 'Commands, place your own commands in the menu bar',
 110: 'Commenting a patch',
 111: 'Compare',
 112: 'Compress a signal',
 113: 'Compute',
 114: 'Computer keyboard events, detect',
 115: 'Concatenate',
 116: 'Concatenate two messages',
 117: 'Conditional statements',
 118: 'Conform file paths',
 119: 'Connect patch cords to an inlet or outlet of a subpatch',
 120: 'Connect',
 121: 'Constant signal of a number',
 122: 'Constrained random movement',
 123: 'Construct MIDI messages for transmission or recording',
 124: 'Construct a list out of individual items',
 125: 'Continue, MIDI system message',
 126: 'Continuous controllers',
 127: 'Control',
 128: 'Controller, picture-based',
 129: 'Convert',
 130: 'Convert colorspaces',
 131: 'Convert Max data types',
 132: 'Convolve two matrices',
 133: "Conway's game of life (cellular automata)",
 134: 'Copy the screen contents into a Jitter matrix',
 135: 'Cosine functions for numbers, matrices and signals',
 136: 'Count how many bang messages or numbers have been received',
 137: 'Count the occurrences of numbers',
 138: 'Count, send a series of numbers as fast as possible',
 139: 'Count',
 140: 'Create',
 141: 'Crossfade between 2 matrices',
 142: 'Crosshatch filter',
 143: 'Crossover filter',
 144: 'Cumulative total of a series of numbers',
 145: 'Cut up a matrix into evenly spaced sub matrices',
 146: 'Cycle a number from outlet to outlet',
 147: 'Cycle messages through outputs',
 148: 'DC offset',
 149: 'Data arriving at different times gets synched',
 150: 'Data smoothing',
 151: 'Data storage',
 152: 'Data structures, arbitrarily ordered array of arbitrary messages',
 153: 'Date and time of day',
 154: 'Decibels',
 155: 'Decrement or increment a value',
 156: 'Defer the execution of a message',
 157: 'Define',
 158: 'Delay',
 159: 'Delta time, report time interval between onsets of MIDI notes',
 160: 'Demultiplex (deinterleave) a single matrix into two',
 161: 'Deprioritize a message',
 162: 'Detect',
 163: 'Devices, drive external devices',
 164: 'Devices, get a list of MIDI devices and ports currently available',
 165: 'Dial user interface',
 166: 'Difference',
 167: 'Digital-to-analog converter',
 168: 'Digitize video from an external source',
 169: 'Disk-based audio playback',
 170: 'Disable signal processing in a subpatch',
 171: 'Disabling part of a signal network',
 172: 'Discrete values from a continuous stream of data',
 173: 'Displace points based on luminance',
 174: 'Display',
 175: 'Distort a sawtooth waveform',
 176: 'Distribute',
 177: 'Divide',
 178: 'Downsampling',
 179: 'Drag and drop',
 180: 'Draw',
 181: 'Duration',
 182: 'Duty cycle of a pulse wave',
 183: 'Edit an audio sample',
 184: 'Eliminate noise in a muted subpatcher',
 185: 'Eliminate number repetitions',
 186: 'Embed a visible subpatcher inside a box',
 187: 'Emboss image',
 188: 'Enable or disable MIDI objects in a patcher automatically',
 189: 'End of a message, add items to',
 190: 'Enter numerical data into a patcher from the computer keyboard',
 191: 'Enter text typed in by the user',
 192: 'Envelope',
 193: 'Equalization',
 194: 'Error messages',
 195: 'Evaluate',
 196: 'Event number, assign to each MIDI note',
 197: 'Event-driven, multi-segment line object',
 198: 'Exclusive or, bitwise XOR operation',
 199: 'Execute Javascript commands sequentially',
 200: 'Execute Javascript',
 201: 'Exponential curve function',
 202: 'Exponential scaling volume slider',
 203: 'Export MIDI file',
 204: 'Expose multiple objects to the pattr system',
 205: 'Expressions, solve mathematical',
 206: 'External clock source, synchronize Max to',
 207: 'Extra precision MIDI pitchbend messages',
 208: 'Extract indexed elements of a list',
 209: 'FIR filter, buffer-based',
 210: 'Fader for displaying or generating numerical data',
 211: 'Fake queue status',
 212: 'Fast Fourier transform',
 213: 'Fast chord detection',
 214: 'Fast fixed filter bank',
 215: 'Feedback a delayed signal',
 216: 'Feedback',
 217: 'File menu, add your own items to',
 218: 'File',
 219: 'Fill a matrix with a list',
 220: 'Film or video, synchronize Max to',
 221: 'Filter (audio)',
 222: 'Filter MIDI',
 223: 'Filter a continuous stream of messages',
 224: 'Filter a signal logarithmically',
 225: 'Filter',
 226: 'Find',
 227: 'FireWire VTR control',
 228: 'Fix file paths and conform',
 229: 'Flanging',
 230: 'Flash on a message',
 231: 'Floating-point data visualization',
 232: 'Floating-point numbers, store numbers with a fractional part',
 233: 'Folder content listings',
 234: 'Follow a performance, comparing it to a pre-recorded sequence',
 235: 'Foreground, move a patcher window automatically to the front',
 236: 'Foreground, notify objects when patcher window is brought to foreground',
 237: 'Format',
 238: 'Forward messages to receive objects',
 239: 'Fourier analysis and synthesis',
 240: 'Fourteen-bit precision MIDI pitchbend messages',
 241: 'FreeFrame Effects for Jitter matrices',
 242: 'Frequency domain',
 243: 'Frequency modulation',
 244: 'Frequency shifter',
 245: 'Frequency-to-pitch conversion',
 246: 'Frequency, keep track of how many times a number has occurred',
 247: 'Full pathname to filename conversion',
 248: 'Function generator',
 249: 'Gating and switching',
 250: 'Gather together a collection of numbers',
 251: 'Generate a bang message',
 252: 'Generate graphics',
 253: 'Generate numbers',
 254: 'Generate MIDI',
 255: 'Generate numbers with the mouse',
 256: 'Generate',
 257: 'Get',
 258: 'Global message-sending',
 259: 'Global signal values',
 260: 'Global variables',
 261: 'Glue many matrices into one',
 262: 'Graph filter poles and zeros on the Z-plane',
 263: 'Graphic display of an array of numbers, editable with the mouse',
 264: 'Graphical',
 265: 'Graphics',
 266: 'Greater than',
 267: 'Greater than, report when all numbers in a list surpass specific '
      'thresholds',
 268: 'Held MIDI notes, provide note-off messages for',
 269: 'Hertz equivalent of a MIDI key number',
 270: 'Hexadecimal display of integer values',
 271: 'Hierarchical on/off switch',
 272: 'Hint, pop-up menu',
 273: 'Histogram of how many times a number has occurred',
 274: 'Hold (store)',
 275: 'Host',
 276: 'Host-synchronized sawtooth wave',
 277: 'Human interface (gaming) device input',
 278: 'Hyperbolic functions for numbers, matrices and signals',
 279: 'IIR filter',
 280: 'Idiosyncratic downsampling/upsampling',
 281: 'If-then-else control structure',
 282: 'Ignore certain messages',
 283: 'Image keying based on distance from a luminance value',
 284: 'Import MIDI file',
 285: 'Impulse generator',
 286: 'In-Patcher Window',
 287: 'Incoming MIDI messages, parse',
 288: 'Increment a value',
 289: 'Index elements of a list and output them individually',
 290: 'Index number, prepend to a number or a list',
 291: 'Indexed list of numerical values',
 292: 'Indicate the zero/non-zero status of a number',
 293: 'Indicator flashes when a message is received',
 294: 'Information about current operating system and hardware',
 295: 'Initialize values automatically when a patch is loaded',
 296: 'Inlet',
 297: 'Input received from MIDI devices, raw',
 298: 'Input received in audio input jack',
 299: 'Input to a delay line',
 300: 'Input to output matrix mapping (256-point char data)',
 301: 'Integer number, store',
 302: 'Integers',
 303: 'Inter-onset interval, measure the time elapsed between two events',
 304: 'Intercept and redirect the output of an object',
 305: 'Interpolate between two numerical values',
 306: 'Interpolating oscillator bank',
 307: 'Interpret',
 308: 'Introduce spatial noise',
 309: 'Inverse fast Fourier transform',
 310: 'Invert the color of a rectangular area of a patcher window over a '
      'picture or a comment',
 311: 'Invert a signal',
 312: 'Invisible button',
 313: 'Invisible patcher',
 314: 'Is equal to, less than, greater than, comparison of numbers, matrices, '
      'or signals',
 315: 'Items of a list, break up into individual messages',
 316: 'Iterate a matrix as a series of Max lists/values',
 317: 'Java',
 318: 'Javascript',
 319: 'Join',
 320: 'Keyboard style slider for displaying and generating numbers',
 321: 'Keyboard, detect computer keyboard events',
 322: 'Keydown event on computer keyboard, detect',
 323: 'Keying based on chromatic distance',
 324: 'Keyup event on computer keyboard, detect',
 325: 'Knob, picture-based',
 326: 'Label objects in a patcher window',
 327: 'Laser disc player, control via the serial port',
 328: 'Last (few) of a series of numbers are retained and sent out separate '
      'outlets',
 329: 'Launch html object reference',
 330: 'Less than/greater than comparisons, redirect numbers based on',
 331: 'Less than - find the lesser of two numbers',
 332: 'Level (audio)',
 333: 'Limit',
 334: 'Limiter',
 335: 'Lindenmayer string expansion (L-systems)',
 336: 'Linear algebra for matrices',
 337: 'Linear ramp generator',
 338: 'Linked list function editor',
 339: 'List processing',
 340: 'List',
 341: 'Lists, array of',
 342: 'Load a patcher automatically',
 343: 'Local variable',
 344: 'Logarithm',
 345: 'Logical expressions',
 346: 'Logical operations using signal values',
 347: 'Look',
 348: 'Lookup table',
 349: 'Loop points in a sound file',
 350: 'Looping a sample',
 351: 'Loops, count repeated events',
 352: 'Loops, repeated series of actions',
 353: 'Lowpass filter',
 354: 'Make',
 355: 'Map-based crossfader',
 356: 'Map',
 357: 'Mark data with number identifying its inlet',
 358: 'Markov chain',
 359: 'Masking, bitwise "and" (intersection) and bitwise "or" (union) '
      'operations',
 360: 'Match',
 361: 'Mathematical expression solving',
 362: 'Matrix utilities',
 363: 'Matrix-style switch control',
 364: 'Matrixctrl-compatible Max message router',
 365: 'Max messages',
 366: 'Max search path information',
 367: 'Maximum and minimum limit for a range of numerical values, specify and '
      'display',
 368: 'Maximum',
 369: 'Measure',
 370: 'Menu bar, customize or alter menus or menu items',
 371: 'Menu, pop-up menu in a patcher',
 372: 'Message',
 373: 'Message symbol substitution',
 374: 'Messages',
 375: 'Meta-imaging',
 376: 'Metronome of timed events',
 377: 'MIDI',
 378: 'Millisecond calculations',
 379: 'Minimum and maximum limit for a range of numerical values, specify and '
      'display',
 380: 'Minimum, find the lesser of two numbers',
 381: 'Minimum, find the minimum value of a group of numbers',
 382: 'Minus, subtract one number from another',
 383: 'Mixing signals',
 384: 'Mixing video',
 385: 'Modem communication, transmit and receive non-MIDI data',
 386: 'Modification date of a file',
 387: 'Modify a signal',
 388: 'Modulation wheel',
 389: 'Modulus operation',
 390: 'Monitor size',
 391: 'Monophonic aftertouch MIDI message',
 392: 'Mouse',
 393: 'Movie, play QuickTime',
 394: 'Multi-media programming',
 395: 'Multi-mode signal average',
 396: 'Multi-purpose list processor',
 397: 'Multi-segment line object, event-driven',
 398: 'Multi-track sequencer of MIDI messages or numbers',
 399: 'Multiplex(interleave) two matrices into one matrix',
 400: 'Multiply',
 401: 'Name user interface objects in a patcher window',
 402: 'Negative number, convert to positive number',
 403: 'Neon glow',
 404: 'Nibble, examine selected bits of a number’s binary representation',
 405: 'Noise gate',
 406: 'Noise',
 407: 'Non-interpolating oscillator bank',
 408: 'Non-zero numbers',
 409: 'Normalize',
 410: 'Not equal to',
 411: 'Not',
 412: 'Note data',
 413: 'Notes in a patch',
 414: 'Note-off messages',
 415: 'Notify Max of a file change',
 416: 'Notify objects when patcher window is moved to foreground or background',
 417: 'Notify user when an event has occurred',
 418: 'Numbers',
 419: 'OMNI Mode On/Off (MIDI Mode message)',
 420: 'Object within an object',
 421: 'Occurrences',
 422: 'Octal, display numbers in Roland octal format',
 423: 'OctiMax dynamics processors',
 424: 'On/Off switch',
 425: 'Only pass different frames',
 426: 'OpenGL',
 427: 'Open',
 428: 'Operating system and hardware information',
 429: 'Optimized blur/sharpen',
 430: 'Or, bitwise exclusive or (XOR) operation',
 431: 'Or, true if one statement or the other is true (logical union)',
 432: 'Order',
 433: 'Oscillators (audio)',
 434: 'Oscilloscope',
 435: 'Outlet',
 436: 'Outlet, send items of an incoming list out individual outlets',
 437: 'Output MIDI data byte by byte',
 438: 'Output a combined list when any element changes',
 439: 'Output audio jack',
 440: 'Output messages',
 441: 'Output numbers',
 442: 'Output the monitor size',
 443: 'Output video',
 444: 'Pack numbers and symbols into a list',
 445: 'Panel',
 446: 'Panic, turn off held MIDI notes',
 447: 'Panning',
 448: 'Parameter change to a MIDI device',
 449: 'Parse MIDI messages',
 450: 'Pass',
 451: 'Patch change MIDI message',
 452: 'Patch cords, connect to an inlet or outlet of a subpatch',
 453: 'Patcher-specific data wrapper',
 454: 'Patcher within a patcher, the contents of which are visible',
 455: 'Peak Limiter',
 456: 'Peak amplitude',
 457: 'Peak hold, keep track of the greatest in a series of numbers',
 458: 'Peek at values in other objects',
 459: 'Perform a GL accelerated grid-based evaluation',
 460: 'Permute a set in random order',
 461: 'Phase distortion synthesis',
 462: 'Phase quadrature filter',
 463: 'Phase shifter',
 464: 'Pick a colour using a dialog box',
 465: 'Picture-based uiser interface object',
 466: 'Pink noise generator',
 467: 'Pitch bend',
 468: 'Pitch shifter for pfft~',
 469: 'Pitch-to-frequency conversion',
 470: 'Pitchbend, report incoming MIDI pitchbend data',
 471: 'Pitchbend, transmit MIDI pitchbend messages',
 472: 'Play a QuickTime movie',
 473: 'Play audio',
 474: 'Play audio file from disk',
 475: 'Play or edit a QuickTime movie',
 476: 'Play sequences of past messages or numbers',
 477: 'Play samples',
 478: 'Plug-in in VST format used in MSP',
 479: 'Point to elements in array by index',
 480: 'Polar to Cartesian coordinate conversion',
 481: 'Poly mode, assign a unique voice number to each note being played',
 482: 'Polyphonic afterpressure',
 483: 'Polyphony management',
 484: 'Pop-up menu in a patcher',
 485: 'Pop-up style hint text',
 486: 'Portamento',
 487: 'Ports, get a list of MIDI devices and ports currently available',
 488: 'Position-based sample playback',
 489: 'Positive version of a negative number',
 490: 'Postpone',
 491: 'Potentiometer-like dial for sending numbers',
 492: 'Power, one number to the power of another',
 493: 'Precise "real-world" time measurements',
 494: 'Prepare',
 495: 'Prepend or append text to a message',
 496: 'Preset, store and recall values for all user interface objects',
 497: 'Prevent multiples of patcher from being opened',
 498: 'Print a matrix as text in the Max window',
 499: 'Print any message in the Max window',
 500: 'Probabilistic (stochastic) decision making',
 501: 'Probability lines',
 502: 'Probability, keep track of how many times a number has occurred',
 503: 'Product of multiplying two numbers',
 504: 'Program change MIDI message',
 505: 'Progress bar, graphic display',
 506: 'Pulse train generator',
 507: 'Pulse wave',
 508: 'Put a visible subpatcher inside a box',
 509: 'Queue-based',
 510: 'QuickDraw graphic commands, draw with',
 511: 'QuickDraw',
 512: 'QuickTime video',
 513: 'QuickTime movie, play',
 514: 'RGB color selection and display swatch',
 515: 'Radio button user interface object',
 516: 'Ramp function, generate',
 517: 'Ramp signal',
 518: 'Random walk',
 519: 'Randomly',
 520: 'Range of numerical values, specify and display minimum and maximum '
      'limits',
 521: 'Rate at which messages are sent, limit',
 522: 'Rate, combine numbers into a single list if received faster than a '
      'certain speed',
 523: 'Rate, control clock speed of Max timing objects',
 524: 'Rate, send out beat numbers at a metronomic tempo',
 525: 'Raw MIDI data, receive and transmit',
 526: 'Raw data from a file, read byte by byte',
 527: 'ReWire device hosting',
 528: 'Read a binary file',
 529: 'Read and draw Wavefront .obj models',
 530: 'Read and write a matrix as an ASCII text file',
 531: 'Read and write a single matrix as a formatted text file',
 532: 'Read and write',
 533: 'Read in a file of binary data',
 534: 'Read matrix data as an audio signal',
 535: 'Read or write an OpenEXR image.',
 536: 'Real-world time measurement',
 537: 'Recall sequences of past messages or numbers',
 538: 'Receive MIDI',
 539: 'Receive any message from any window',
 540: 'Receive matrices from a jit.net.send object via TCP/IP',
 541: 'Receive messages',
 542: 'Receive only specific MIDI messages',
 543: 'Recently received values are stored and recalled',
 544: 'Record',
 545: 'Recording audio samples',
 546: 'Redirect messages to a specific destination',
 547: 'Reference a sub-region of a matrix',
 548: 'Release velocity, detecting and formatting note-off messages with',
 549: 'Remainder',
 550: 'Remap and/or invert matrix dimensions',
 551: 'Remote connection of objects, without patch cords',
 552: 'Remove redundant dimensions of size 1',
 553: 'Render OpenGL',
 554: 'Reorder grid of rectangles',
 555: 'Repeatedly send bang messages as fast as possible',
 556: 'Repeatedly send output at a certain rate',
 557: 'Repetition at sub-audio rates',
 558: 'Repetitions, count',
 559: 'Repetitions, suppress repeated numbers',
 560: 'Replace NaN and infinite signal values with 0',
 561: 'Report',
 562: 'Reposition spatially',
 563: 'Reproduce a single bang to different places in immediate succession',
 564: 'Resample by scanline wrapping',
 565: 'Resample spatially',
 566: 'Resonant filter',
 567: 'Restrict numbers to a certain range',
 568: 'Reverberation',
 569: 'Reverse output with respect to input',
 570: 'Reverse the order of two number messages',
 571: 'ReWire',
 572: 'Reverse',
 573: 'Reversed sample playback',
 574: 'Ring modulation',
 575: 'Ritardando, control clock speed of Max timing objects',
 576: "Robert's Cross edge detection",
 577: 'Rotate elements of a set of numbers, out successive outlets',
 578: 'Rotate hue',
 579: 'Rotate',
 580: 'Rotate a Video image',
 581: 'Round an input signal value',
 582: 'Route',
 583: 'Route a signal',
 584: 'Run a Javascript',
 585: 'SMPTE time code, synchronize to an external source via MIDI Manager',
 586: 'Sample and hold',
 587: 'Sample index in a buffer',
 588: 'Sample playback without interpolation',
 589: 'Sample playback',
 590: 'Sampler, receive and transmit sound data via MIDI Sample Dump',
 591: 'Sampling and audio buffers',
 592: 'Sampling rate',
 593: 'Save, move to the foreground, or close a patcher window automatically',
 594: 'Save',
 595: 'Sawtooth oscillator',
 596: 'Sawtooth wave generator',
 597: 'Scale on the basis of maximum amplitude',
 598: 'Scale/rotate an inage in 2D',
 599: 'Scale',
 600: 'Schedule a number or list to be sent at a future time',
 601: 'Schedule an event for a future time',
 602: 'Score-following',
 603: 'Screen size',
 604: 'Scroll through a list of messages',
 605: 'Search path information',
 606: 'See the maximum amplitude of a signal',
 607: 'Select',
 608: 'Selectively pass an input to an outlet',
 609: 'Send a bang',
 610: 'Send matrices to a jit.net.recv object via TCP/IP',
 611: 'Send message(s)',
 612: 'Send MIDI',
 613: 'Send numbers',
 614: 'Send',
 615: 'Separate a list into its constituent elements',
 616: 'Sequence of numbers, detect a specific ordered set of numbers',
 617: 'Sequence of numbers, generate automatically',
 618: 'Sequencer',
 619: 'Serial port, transmit and receive non-MIDI data',
 620: 'Series of numbers, break a list up into individual messages',
 621: 'Series of numbers, combine into a single list',
 622: 'Set (of fixed order and size) of integers; output all whenever one is '
      'modified',
 623: 'Set background color',
 624: 'Set values automatically when a patch is loaded',
 625: 'Set/query monitor attributes',
 626: 'Set, produce a random ordering of a set',
 627: 'Set, store an unordered set of numbers',
 628: 'Set',
 629: 'Share variables',
 630: 'Shift bits to left or right',
 631: 'Shift sequential input from one outlet to another',
 632: 'Show',
 633: 'Signal analysis',
 634: 'Signal averaging',
 635: 'Signal capture and granular oscillator',
 636: 'Signal folding, variable range',
 637: 'Signal monitor and constant generator',
 638: 'Signal spectrogram or sonogram',
 639: 'Signal-driven sequencers',
 640: 'Signal-rate filter coefficient generator',
 641: 'Signal routing',
 642: 'Simultaneity, send a series of bang messages or numbers in a single '
      'tick of Max’s clock',
 643: 'Sine functions',
 644: 'Sine functions for numbers, matrices and signals',
 645: 'Single-pole lowpass filter',
 646: 'Slider to display or generate numerical data',
 647: 'Smooth an incoming signal',
 648: 'Snapshot, store and recall instantaneous values of all user interface '
      'objects',
 649: 'Sobel and Prewitt gradient edge detector',
 650: 'Soft-clipping signal distortion',
 651: 'Solve',
 652: 'Sonogram',
 653: 'Sound sample data, receive and transmit via MIDI Sample Dump',
 654: 'Sound, play in a QuickTime movie',
 655: 'Sparse array of numbers',
 656: 'Spatial transform using 3x3 matrix',
 657: 'Spearate numbers into ranges',
 658: 'Spectral domain processing',
 659: 'Spectral processing manager for patchers',
 660: 'Spectrogram',
 661: 'Spectrum measurement',
 662: 'Speed, combine numbers into a single list if received faster than a '
      'certain rate',
 663: 'Speed, limit the rate at which messages are sent',
 664: 'Split a matrix into two matrices',
 665: 'Split a stream of data between individual outlets',
 666: 'Sprites, pictures and geometric shapes',
 667: 'Square root',
 668: 'Start a process by sending the bang message',
 669: 'Start activity automatically when a patch is loaded',
 670: 'Start and end point of a sample',
 671: 'Start, MIDI system message',
 672: 'State-variable filter with simultaneous outputs',
 673: 'Steal voices, turn off old notes if too many new ones arrive',
 674: 'Stochastic (probabilistic) decision making',
 675: 'Stop or alter the flow of messages',
 676: 'Stop, MIDI system message',
 677: 'Store',
 678: 'String of text combining numbers, ASCII bytes, and symbols into a '
      'single message',
 679: 'String/matrix utilities',
 680: 'Stuck MIDI notes, avoid or turn off',
 681: 'Subpatch control',
 682: 'Subpatch in a box, visible from the patcher that contains it',
 683: 'Subpatch object (subroutine)',
 684: 'Subpatch object, create an inlet or outlet in',
 685: 'Substitute a symbol for another symbol in a message',
 686: 'Substitute',
 687: 'Subtract',
 688: 'Subtractive synthesis',
 689: 'Sum of a set of numbers',
 690: 'Suppress note-off messages',
 691: 'Suppress the flow of certain messages',
 692: 'Sustain notes by holding note-off messages until a specific event '
      'occurs',
 693: 'Sustain pedal',
 694: 'Swap',
 695: 'Switch a process on and off',
 696: 'Switch between zero and one',
 697: 'Switch control matrix',
 698: 'Switch the flow of messages on or off',
 699: 'Switching signal flow on and off',
 700: 'Symbol to message conversion',
 701: 'Synchronize MSP with an external source',
 702: 'Synchronize Max to an external clock source',
 703: 'Synchronize asynchronously arriving inputs, send them out together',
 704: 'Synchronize',
 705: 'System Reset, MIDI system message',
 706: 'System exclusive messages, construct and transmit',
 707: 'System exclusive messages, receive',
 708: 'Table lookup',
 709: 'Tag data with number identifying its inlet',
 710: 'Tag messages with a unique index number',
 711: 'Tangent functions for numbers, matrices and signals',
 712: 'Tempo, control clock speed of Max timing objects',
 713: 'Tempo, send out beat numbers at a metronomic tempo',
 714: 'Test the equality of two numbers',
 715: 'Test the zero/non-zero status of a number or expression',
 716: 'Test whether one number is greater than another',
 717: 'Test whether one number is less than another',
 718: 'Text file of signal samples',
 719: 'Text file, load, play, and save a MIDI file as plain text',
 720: 'Text file, open and save',
 721: 'Text input by the user, obtain',
 722: 'Text, convert to ASCII numbers',
 723: 'Text, display automatically in a patcher',
 724: 'Text, display in a patcher',
 725: 'Text, format numbers, ASCII bytes, and symbols into a single message',
 726: 'Text, print any message in the Max window',
 727: 'The Jitter Matrix!',
 728: 'Third-order crossover filter',
 729: 'Threshold, report when numbers surpass',
 730: 'Timbre change on a MIDI synthesizer',
 731: 'Time code, receive from an external source',
 732: 'Time elapsed between events, check',
 733: 'Time measurement in cpu cycles',
 734: 'Time of day and date',
 735: 'Time-domain frequency shifter',
 736: 'Time-domain frequency shifter',
 737: 'Time-scale the output of a phasor~',
 738: 'Times, multiply two numbers',
 739: 'Toggle a process on and off',
 740: 'Toggle',
 741: 'Track, record and play back a multi-track sequence of messages or '
      'numbers',
 742: 'Traffic control for bang messages',
 743: 'Transfer function lookup tables',
 744: 'Transform symbol(s) into messages and numbers',
 745: 'Transforms matrix data into signals',
 746: 'Transforms signal data into matrices',
 747: 'Transient detector',
 748: 'Transition probabilities, Markov chain',
 749: 'Transmit MIDI',
 750: 'Transmit a specific MIDI message type',
 751: 'Transmit signals without patch cords',
 752: 'Trap',
 753: 'Trapezoidal wavetable',
 754: 'Triangle/ramp wavetable',
 755: 'Trigger',
 756: 'Trigonometric functions',
 757: 'Trigonometric operators',
 758: 'True matrix multiplication',
 759: 'True/false testing',
 760: 'Truncate the fractional part of a signal',
 761: 'Turn',
 762: 'turtle graphics interpreter in 2d',
 763: 'Two-dimensional storage and viewing',
 764: 'Two-dimensional wavetable',
 765: 'Two-pole, two-zero filter',
 766: 'Type numerical data into a patcher',
 767: 'Type text into a locked patcher',
 768: 'Unroll a matrix into a list',
 769: 'Use PERL-compatible regular expressions on Jitter matrices',
 770: 'Use mouse movement to control position/rotation',
 771: 'Use the alpha channel of one image to blend two images together',
 772: 'Use PERL-style regular expressions to process input',
 773: 'User input, ask for',
 774: 'User input',
 775: 'User interface: dial',
 776: 'Uses a 1-dimensional matrix to offset scanlines',
 777: 'Uses matrices to draw multiple instances of a jit.gl object efficiently',
 778: 'Variable',
 779: 'Variable range signal folding',
 780: 'Variable size wavetable',
 781: 'Variable-rate looping sample playback',
 782: 'Varispeed sample playback',
 783: 'Vector math, evaluate an expression multiple times using lists of '
      'numbers as input',
 784: 'Vector size',
 785: 'Vector-based envelope follower',
 786: 'Velocity (MIDI) control of a signal',
 787: 'Velocity of incoming MIDI note-on messages, obtain',
 788: 'Velocity, detecting and formatting note-off messages with release '
      'velocity',
 789: 'Video or film, synchronize Max to',
 790: 'Video display',
 791: 'Videodisc player, control via the serial port',
 792: 'Video image filters',
 793: 'Video mixing and compositing',
 794: 'View a signal',
 795: 'Virtual connection of objects, without patch cords',
 796: 'Visual RMS level indicator',
 797: 'Visual peak level indicator',
 798: 'Voice number, assign a unique number to each note being played',
 799: 'Voice stealing, turn off old notes if too many new ones arrive',
 800: 'Volume control MIDI message',
 801: 'Volume control of a QuickTime movie',
 802: 'Wait before allowing a number to pass',
 803: 'Wait before doing something',
 804: 'Wait for input in both inlets, then send out both numbers',
 805: 'Watch for file change and report',
 806: 'Waveshaping',
 807: 'Wavetable synthesis',
 808: 'Wavetables',
 809: 'Webcam input',
 810: 'Weighted probabilities',
 811: 'White noise generator',
 812: 'Window being closed sends a bang',
 813: 'Window moving to foreground or background sends 1 or 0',
 814: 'Window on a subpatch seen within the patcher that contains that '
      'subpatch',
 815: 'Window, enable or disable MIDI automatically',
 816: 'Window, open and close automatically',
 817: 'Windowing a portion of a signal',
 818: 'Windows, communicate between',
 819: 'Wrap a signal between -π and π',
 820: 'Write a comment in the patch',
 821: 'Write an audio signal into a matrix',
 822: 'Write bitmap text',
 823: 'Write sample values by index',
 824: 'Write vector text',
 825: 'XOR, bitwise "exclusive or" operation',
 826: 'X-Y plotting of a two-plane matrix',
 827: 'Zero and non-zero numbers, notify when input changes from one to the '
      'other',
 828: 'Zero-cross counter',
 829: 'Zero, test if a number or expression is equal to',
 830: 'Zooming/cropping a Video image'}
 
objects = {
 '!-': ('/max8/refpages/rminus', 687),
 '!-~': ('/max8/refpages/rminus~', 687),
 '!/': ('/max8/refpages/rdiv', 177),
 '!/~': ('/max8/refpages/rdiv', 177),
 '!=': ('/max8/refpages/notequals', 829),
 '!=~': ('/max8/refpages/notequals~', 66),
 '%': ('/max8/refpages/modulo', 651),
 '%~': ('/max8/refpages/modulo~', 549),
 '&': ('/max8/refpages/bitand', 418),
 '&&': ('/max8/refpages/logand', 829),
 '*': ('/max8/refpages/times', 738),
 '*~': ('/max8/refpages/times~', 574),
 '+': ('/max8/refpages/plus', 689),
 '+=~': ('/max8/refpages/plusequals~', 14),
 '+~': ('/max8/refpages/plus~', 243),
 '-': ('/max8/refpages/minus', 687),
 '-~': ('/max8/refpages/minus~', 687),
 '/': ('/max8/refpages/div', 651),
 '/~': ('/max8/refpages/div~', 409),
 '2d.wave~': ('/max8/refpages/2d.wave~', 807),
 '<': ('/max8/refpages/lessthan', 759),
 '<<': ('/max8/refpages/shiftleft', 630),
 '<=': ('/max8/refpages/lessthaneq', 759),
 '<=~': ('/max8/refpages/lessthaneq~', 66),
 '<~': ('/max8/refpages/lessthan~', 507),
 '==': ('/max8/refpages/equals', 829),
 '==~': ('/max8/refpages/equals~', 346),
 '>': ('/max8/refpages/greaterthan', 759),
 '>=': ('/max8/refpages/greaterthaneq', 759),
 '>=~': ('/max8/refpages/greaterthaneq~', 66),
 '>>': ('/max8/refpages/shiftright', 630),
 '>~': ('/max8/refpages/greaterthan~', 507),
 'abs': ('/max8/refpages/abs', 489),
 'absolutepath': ('/max8/refpages/absolutepath', 129),
 'abs~': ('/max8/refpages/abs~', 9),
 'accum': ('/max8/refpages/accum', 738),
 'acos': ('/max8/refpages/acos', 757),
 'acosh': ('/max8/refpages/acosh', 757),
 'acosh~': ('/max8/refpages/acosh~', 757),
 'acos~': ('/max8/refpages/acos~', 757),
 'active': ('/max8/refpages/active', 813),
 'adc~': ('/max8/refpages/adc~', 784),
 'adoutput~': ('/max8/refpages/adoutput~', 52),
 'adsr~': ('/max8/refpages/adsr~', 786),
 'adstatus': ('/max8/refpages/adstatus', 561),
 'allpass~': ('/max8/refpages/allpass~', 688),
 'anal': ('/max8/refpages/anal', 354),
 'append': ('/max8/refpages/append', 495),
 'asin': ('/max8/refpages/asin', 757),
 'asinh': ('/max8/refpages/asinh', 757),
 'asinh~': ('/max8/refpages/asinh~', 757),
 'asin~': ('/max8/refpages/asin~', 757),
 'atan': ('/max8/refpages/atan', 757),
 'atan2': ('/max8/refpages/atan2', 757),
 'atan2~': ('/max8/refpages/atan2~', 757),
 'atanh': ('/max8/refpages/atanh', 757),
 'atanh~': ('/max8/refpages/atanh~', 757),
 'atan~': ('/max8/refpages/atan~', 757),
 'atodb': ('/max8/refpages/atodb', 154),
 'atodb~': ('/max8/refpages/atodb~', 129),
 'atoi': ('/max8/refpages/atoi', 302),
 'autopattr': ('/max8/refpages/autopattr', 204),
 'average~': ('/max8/refpages/average~', 395),
 'avg~': ('/max8/refpages/avg~', 634),
 'bag': ('/max8/refpages/bag', 677),
 'bangbang': ('/max8/refpages/bangbang', 609),
 'begin~': ('/max8/refpages/begin~', 641),
 'bendin': ('/max8/refpages/bendin', 542),
 'bendout': ('/max8/refpages/bendout', 750),
 'bgcolor': ('/max8/refpages/bgcolor', 628),
 'biquad~': ('/max8/refpages/biquad~', 765),
 'bitand': ('/max8/refpages/bitand', 65),
 'bitand~': ('/max8/refpages/bitand~', 65),
 'bitnot~': ('/max8/refpages/bitnot~', 65),
 'bitor': ('/max8/refpages/bitor', 65),
 'bitor~': ('/max8/refpages/bitor~', 65),
 'bitsafe~': ('/max8/refpages/bitsafe~', 560),
 'bitshift~': ('/max8/refpages/bitshift~', 63),
 'bitxor~': ('/max8/refpages/bitxor~', 65),
 'bline': ('/max8/refpages/bline', 397),
 'bondo': ('/max8/refpages/bondo', 704),
 'borax': ('/max8/refpages/borax', 798),
 'bpatcher': ('/max8/refpages/bpatcher', 814),
 'bucket': ('/max8/refpages/bucket', 677),
 'buddy': ('/max8/refpages/buddy', 804),
 'buffer~': ('/max8/refpages/buffer~', 807),
 'buffir~': ('/max8/refpages/buffir~', 221),
 'button': ('/max8/refpages/button', 755),
 'capture': ('/max8/refpages/capture', 677),
 'capture~': ('/max8/refpages/capture~', 794),
 'cartopol': ('/max8/refpages/cartopol', 129),
 'cartopol~': ('/max8/refpages/cartopol~', 658),
 'cascade~': ('/max8/refpages/cascade~', 221),
 'change': ('/max8/refpages/change', 829),
 'change~': ('/max8/refpages/change~', 633),
 'click~': ('/max8/refpages/click~', 285),
 'clip': ('/max8/refpages/clip', 567),
 'clip~': ('/max8/refpages/clip~', 507),
 'clocker': ('/max8/refpages/clocker', 732),
 'closebang': ('/max8/refpages/closebang', 812),
 'coll': ('/max8/refpages/coll', 677),
 'colorpicker': ('/max8/refpages/colorpicker', 607),
 'comb~': ('/max8/refpages/comb~', 688),
 'comment': ('/max8/refpages/comment', 820),
 'conformpath': ('/max8/refpages/conformpath', 228),
 'cos': ('/max8/refpages/cos', 757),
 'cosh': ('/max8/refpages/cosh', 757),
 'cosh~': ('/max8/refpages/cosh~', 757),
 'cosx~': ('/max8/refpages/cosx~', 757),
 'cos~': ('/max8/refpages/cos~', 757),
 'counter': ('/max8/refpages/counter', 617),
 'count~': ('/max8/refpages/count~', 633),
 'cpuclock': ('/max8/refpages/cpuclock', 733),
 'cross~': ('/max8/refpages/cross~', 728),
 'ctlin': ('/max8/refpages/ctlin', 800),
 'ctlout': ('/max8/refpages/ctlout', 800),
 'curve~': ('/max8/refpages/curve~', 786),
 'cycle': ('/max8/refpages/cycle', 665),
 'cycle~': ('/max8/refpages/cycle~', 817),
 'dac~': ('/max8/refpages/dac~', 784),
 'date': ('/max8/refpages/date', 734),
 'dbtoa': ('/max8/refpages/dbtoa', 154),
 'dbtoa~': ('/max8/refpages/dbtoa~', 129),
 'decide': ('/max8/refpages/decide', 519),
 'decode': ('/max8/refpages/decode', 424),
 'defer': ('/max8/refpages/defer', 161),
 'deferlow': ('/max8/refpages/deferlow', 158),
 'degrade~': ('/max8/refpages/degrade~', 387),
 'delay': ('/max8/refpages/delay', 803),
 'delay~': ('/max8/refpages/delay~', 158),
 'deltaclip~': ('/max8/refpages/deltaclip~', 387),
 'delta~': ('/max8/refpages/delta~', 387),
 'detonate': ('/max8/refpages/detonate', 264),
 'dial': ('/max8/refpages/dial', 775),
 'dialog': ('/max8/refpages/dialog', 773),
 'downsamp~': ('/max8/refpages/downsamp~', 387),
 'dropfile': ('/max8/refpages/dropfile', 179),
 'drunk': ('/max8/refpages/drunk', 810),
 'dspstate~': ('/max8/refpages/dspstate~', 784),
 'dsptime~': ('/max8/refpages/dsptime~', 561),
 'edge~': ('/max8/refpages/edge~', 755),
 'error': ('/max8/refpages/error', 761),
 'expr': ('/max8/refpages/expr', 825),
 'ezadc~': ('/max8/refpages/ezadc~', 545),
 'ezdac~': ('/max8/refpages/ezdac~', 473),
 'fbinshift~': ('/max8/refpages/fbinshift~', 244),
 'fffb~': ('/max8/refpages/fffb~', 221),
 'fftinfo~': ('/max8/refpages/fftinfo~', 658),
 'fftin~': ('/max8/refpages/fftin~', 658),
 'fftout~': ('/max8/refpages/fftout~', 658),
 'fft~': ('/max8/refpages/fft~', 661),
 'filedate': ('/max8/refpages/filedate', 561),
 'filein': ('/max8/refpages/filein', 533),
 'filepath': ('/max8/refpages/filepath', 605),
 'filewatch': ('/max8/refpages/filewatch', 805),
 'filtercoeff~': ('/max8/refpages/filtercoeff~', 640),
 'filtergraph~': ('/max8/refpages/filtergraph~', 264),
 'float': ('/max8/refpages/float', 818),
 'flush': ('/max8/refpages/flush', 761),
 'folder': ('/max8/refpages/folder', 427),
 'follow': ('/max8/refpages/follow', 755),
 'fontlist': ('/max8/refpages/fontlist', 340),
 'forward': ('/max8/refpages/forward', 818),
 'fpic': ('/max8/refpages/fpic', 724),
 'frameaccum~': ('/max8/refpages/frameaccum~', 658),
 'framedelta~': ('/max8/refpages/framedelta~', 658),
 'freqshift~': ('/max8/refpages/freqshift~', 736),
 'fromsymbol': ('/max8/refpages/fromsymbol', 744),
 'fswap': ('/max8/refpages/fswap', 694),
 'ftom': ('/max8/refpages/ftom', 377),
 'ftom~': ('/max8/refpages/ftom~', 129),
 'funbuff': ('/max8/refpages/funbuff', 677),
 'function': ('/max8/refpages/function', 708),
 'funnel': ('/max8/refpages/funnel', 710),
 'gain~': ('/max8/refpages/gain~', 786),
 'gate': ('/max8/refpages/gate', 698),
 'gate~': ('/max8/refpages/gate~', 817),
 'gestalt': ('/max8/refpages/gestalt', 428),
 'ggate': ('/max8/refpages/gswitch2', 740),
 'gizmo~': ('/max8/refpages/gizmo~', 468),
 'grab': ('/max8/refpages/grab', 818),
 'groove~': ('/max8/refpages/groove~', 782),
 'gswitch': ('/max8/refpages/gswitch', 740),
 'hi': ('/max8/refpages/hi', 774),
 'hilbert~': ('/max8/refpages/hilbert~', 462),
 'hint': ('/max8/refpages/hint', 485),
 'histo': ('/max8/refpages/histo', 502),
 'hostcontrol~': ('/max8/refpages/hostcontrol~', 127),
 'hostphasor~': ('/max8/refpages/hostphasor~', 571),
 'hostsync~': ('/max8/refpages/hostsync~', 571),
 'if': ('/max8/refpages/if', 829),
 'ifft~': ('/max8/refpages/ifft~', 661),
 'imovie': ('/max8/refpages/imovie', 752),
 'in': ('/max8/refpages/in', 483),
 'incdec': ('/max8/refpages/incdec', 288),
 'index~': ('/max8/refpages/index~', 817),
 'info~': ('/max8/refpages/info~', 591),
 'inlet': ('/max8/refpages/inlet', 818),
 'int': ('/max8/refpages/int', 818),
 'in~': ('/max8/refpages/in~', 483),
 'ioscbank~': ('/max8/refpages/ioscbank~', 433),
 'iter': ('/max8/refpages/iter', 620),
 'itoa': ('/max8/refpages/itoa', 129),
 'jit.3m': ('/max8/refpages/jit.3m', 561),
 'jit.alphablend': ('/max8/refpages/jit.alphablend', 793),
 'jit.altern': ('/max8/refpages/jit.altern', 101),
 'jit.ameba': ('/max8/refpages/jit.ameba', 792),
 'jit.argb2ayuv': ('/max8/refpages/jit.argb2ayuv', 130),
 'jit.argb2grgb': ('/max8/refpages/jit.argb2grgb', 130),
 'jit.argb2uyvy': ('/max8/refpages/jit.argb2uyvy', 130),
 'jit.avc': ('/max8/refpages/jit.avc', 227),
 'jit.avg4': ('/max8/refpages/jit.avg4', 792),
 'jit.ayuv2argb': ('/max8/refpages/jit.ayuv2argb', 130),
 'jit.ayuv2luma': ('/max8/refpages/jit.ayuv2luma', 130),
 'jit.ayuv2uyvy': ('/max8/refpages/jit.ayuv2uyvy', 130),
 'jit.bfg': ('/max8/refpages/jit.bfg', 195),
 'jit.brass': ('/max8/refpages/jit.brass', 792),
 'jit.brcosa': ('/max8/refpages/jit.brcosa', 793),
 'jit.bsort': ('/max8/refpages/jit.bsort', 792),
 'jit.buffer~': ('/max8/refpages/jit.buffer~', 131),
 'jit.catch~': ('/max8/refpages/jit.catch~', 746),
 'jit.cellblock': ('/max8/refpages/jit.cellblock', 763),
 'jit.change': ('/max8/refpages/jit.change', 425),
 'jit.charmap': ('/max8/refpages/jit.charmap', 792),
 'jit.chromakey': ('/max8/refpages/jit.chromakey', 323),
 'jit.clip': ('/max8/refpages/jit.clip', 792),
 'jit.coerce': ('/max8/refpages/jit.coerce', 362),
 'jit.colorspace': ('/max8/refpages/jit.colorspace', 129),
 'jit.concat': ('/max8/refpages/jit.concat', 115),
 'jit.convolve': ('/max8/refpages/jit.convolve', 792),
 'jit.conway': ('/max8/refpages/jit.conway', 792),
 'jit.cycle': ('/max8/refpages/jit.cycle', 147),
 'jit.demultiplex': ('/max8/refpages/jit.demultiplex', 792),
 'jit.desktop': ('/max8/refpages/jit.desktop', 134),
 'jit.dimmap': ('/max8/refpages/jit.dimmap', 550),
 'jit.displays': ('/max8/refpages/jit.displays', 625),
 'jit.dx.grab': ('/max8/refpages/jit.dx.grab', 809),
 'jit.dx.videoout': ('/max8/refpages/jit.dx.videoout', 443),
 'jit.eclipse': ('/max8/refpages/jit.eclipse', 792),
 'jit.expr': ('/max8/refpages/jit.expr', 687),
 'jit.fastblur': ('/max8/refpages/jit.fastblur', 792),
 'jit.fft': ('/max8/refpages/jit.fft', 212),
 'jit.fill': ('/max8/refpages/jit.fill', 679),
 'jit.findbounds': ('/max8/refpages/jit.findbounds', 81),
 'jit.fluoride': ('/max8/refpages/jit.fluoride', 792),
 'jit.fprint': ('/max8/refpages/jit.fprint', 531),
 'jit.fpsgui': ('/max8/refpages/jit.fpsgui', 790),
 'jit.freeframe': ('/max8/refpages/jit.freeframe', 241),
 'jit.gencoord': ('/max8/refpages/jit.gencoord', 195),
 'jit.gl.graph': ('/max8/refpages/jit.gl.graph', 426),
 'jit.gl.gridshape': ('/max8/refpages/jit.gl.gridshape', 426),
 'jit.gl.handle': ('/max8/refpages/jit.gl.handle', 770),
 'jit.gl.imageunit': ('/max8/refpages/jit.gl.imageunit', 553),
 'jit.gl.isosurf': ('/max8/refpages/jit.gl.isosurf', 252),
 'jit.gl.mesh': ('/max8/refpages/jit.gl.mesh', 252),
 'jit.gl.model': ('/max8/refpages/jit.gl.model', 529),
 'jit.gl.multiple': ('/max8/refpages/jit.gl.multiple', 777),
 'jit.gl.nurbs': ('/max8/refpages/jit.gl.nurbs', 426),
 'jit.gl.plato': ('/max8/refpages/jit.gl.plato', 426),
 'jit.gl.render': ('/max8/refpages/jit.gl.render', 553),
 'jit.gl.sketch': ('/max8/refpages/jit.gl.sketch', 426),
 'jit.gl.slab': ('/max8/refpages/jit.gl.slab', 459),
 'jit.gl.text2d': ('/max8/refpages/jit.gl.text2d', 822),
 'jit.gl.text3d': ('/max8/refpages/jit.gl.text3d', 824),
 'jit.gl.videoplane': ('/max8/refpages/jit.gl.videoplane', 830),
 'jit.gl.volume': ('/max8/refpages/jit.gl.volume', 140),
 'jit.glop': ('/max8/refpages/jit.glop', 792),
 'jit.glue': ('/max8/refpages/jit.glue', 261),
 'jit.gradient': ('/max8/refpages/jit.gradient', 252),
 'jit.graph': ('/max8/refpages/jit.graph', 231),
 'jit.grgb2argb': ('/max8/refpages/jit.grgb2argb', 130),
 'jit.hatch': ('/max8/refpages/jit.hatch', 792),
 'jit.histogram': ('/max8/refpages/jit.histogram', 81),
 'jit.hsl2rgb': ('/max8/refpages/jit.hsl2rgb', 130),
 'jit.hue': ('/max8/refpages/jit.hue', 793),
 'jit.iter': ('/max8/refpages/jit.iter', 316),
 'jit.keyscreen': ('/max8/refpages/jit.keyscreen', 792),
 'jit.la.determinant': ('/max8/refpages/jit.la.determinant', 336),
 'jit.la.diagproduct': ('/max8/refpages/jit.la.diagproduct', 336),
 'jit.la.inverse': ('/max8/refpages/jit.la.inverse', 336),
 'jit.la.mult': ('/max8/refpages/jit.la.mult', 758),
 'jit.la.trace': ('/max8/refpages/jit.la.trace', 336),
 'jit.la.uppertri': ('/max8/refpages/jit.la.uppertri', 336),
 'jit.lcd': ('/max8/refpages/jit.lcd', 793),
 'jit.linden': ('/max8/refpages/jit.linden', 679),
 'jit.luma2ayuv': ('/max8/refpages/jit.luma2ayuv', 130),
 'jit.luma2uyvy': ('/max8/refpages/jit.luma2uyvy', 130),
 'jit.lumakey': ('/max8/refpages/jit.lumakey', 792),
 'jit.map': ('/max8/refpages/jit.map', 356),
 'jit.matrix': ('/max8/refpages/jit.matrix', 830),
 'jit.matrixinfo': ('/max8/refpages/jit.matrixinfo', 561),
 'jit.matrixset': ('/max8/refpages/jit.matrixset', 677),
 'jit.multiplex': ('/max8/refpages/jit.multiplex', 792),
 'jit.mxform2d': ('/max8/refpages/jit.mxform2d', 793),
 'jit.net.recv': ('/max8/refpages/jit.net.recv', 540),
 'jit.net.send': ('/max8/refpages/jit.net.send', 610),
 'jit.noise': ('/max8/refpages/jit.noise', 811),
 'jit.normalize': ('/max8/refpages/jit.normalize', 409),
 'jit.obref': ('/max8/refpages/jit.obref', 329),
 'jit.op': ('/max8/refpages/jit.op', 793),
 'jit.openexr': ('/max8/refpages/jit.openexr', 535),
 'jit.p.bounds': ('/max8/refpages/jit.p.bounds', 333),
 'jit.p.shiva': ('/max8/refpages/jit.p.shiva', 252),
 'jit.p.vishnu': ('/max8/refpages/jit.p.vishnu', 252),
 'jit.pack': ('/max8/refpages/jit.pack', 354),
 'jit.peek~': ('/max8/refpages/jit.peek~', 534),
 'jit.plot': ('/max8/refpages/jit.plot', 826),
 'jit.plume': ('/max8/refpages/jit.plume', 792),
 'jit.plur': ('/max8/refpages/jit.plur', 792),
 'jit.poke~': ('/max8/refpages/jit.poke~', 821),
 'jit.print': ('/max8/refpages/jit.print', 498),
 'jit.pwindow': ('/max8/refpages/jit.pwindow', 790),
 'jit.qball': ('/max8/refpages/jit.qball', 129),
 'jit.qfaker': ('/max8/refpages/jit.qfaker', 211),
 'jit.qt.broadcast': ('/max8/refpages/jit.qt.broadcast', 71),
 'jit.qt.effect': ('/max8/refpages/jit.qt.effect', 512),
 'jit.qt.grab': ('/max8/refpages/jit.qt.grab', 809),
 'jit.qt.movie': ('/max8/refpages/jit.qt.movie', 512),
 'jit.qt.record': ('/max8/refpages/jit.qt.record', 544),
 'jit.qt.videoout': ('/max8/refpages/jit.qt.videoout', 512),
 'jit.release~': ('/max8/refpages/jit.release~', 745),
 'jit.repos': ('/max8/refpages/jit.repos', 792),
 'jit.resamp': ('/max8/refpages/jit.resamp', 792),
 'jit.reverse': ('/max8/refpages/jit.reverse', 569),
 'jit.rgb2luma': ('/max8/refpages/jit.rgb2luma', 130),
 'jit.robcross': ('/max8/refpages/jit.robcross', 792),
 'jit.rota': ('/max8/refpages/jit.rota', 830),
 'jit.roy': ('/max8/refpages/jit.roy', 792),
 'jit.rubix': ('/max8/refpages/jit.rubix', 792),
 'jit.scalebias': ('/max8/refpages/jit.scalebias', 793),
 'jit.scanoffset': ('/max8/refpages/jit.scanoffset', 792),
 'jit.scanslide': ('/max8/refpages/jit.scanslide', 792),
 'jit.scanwrap': ('/max8/refpages/jit.scanwrap', 792),
 'jit.scissors': ('/max8/refpages/jit.scissors', 145),
 'jit.shade': ('/max8/refpages/jit.shade', 355),
 'jit.slide': ('/max8/refpages/jit.slide', 792),
 'jit.sobel': ('/max8/refpages/jit.sobel', 792),
 'jit.spill': ('/max8/refpages/jit.spill', 768),
 'jit.split': ('/max8/refpages/jit.split', 664),
 'jit.sprinkle': ('/max8/refpages/jit.sprinkle', 792),
 'jit.str.fromsymbol': ('/max8/refpages/jit.str.fromsymbol', 679),
 'jit.str.op': ('/max8/refpages/jit.str.op', 679),
 'jit.str.regexp': ('/max8/refpages/jit.str.regexp', 769),
 'jit.str.tosymbol': ('/max8/refpages/jit.str.tosymbol', 679),
 'jit.streak': ('/max8/refpages/jit.streak', 792),
 'jit.submatrix': ('/max8/refpages/jit.submatrix', 547),
 'jit.textfile': ('/max8/refpages/jit.textfile', 530),
 'jit.thin': ('/max8/refpages/jit.thin', 552),
 'jit.tiffany': ('/max8/refpages/jit.tiffany', 792),
 'jit.traffic': ('/max8/refpages/jit.traffic', 792),
 'jit.transpose': ('/max8/refpages/jit.transpose', 792),
 'jit.turtle': ('/max8/refpages/jit.turtle', 762),
 'jit.unpack': ('/max8/refpages/jit.unpack', 354),
 'jit.uyvy2argb': ('/max8/refpages/jit.uyvy2argb', 130),
 'jit.uyvy2ayuv': ('/max8/refpages/jit.uyvy2ayuv', 130),
 'jit.uyvy2luma': ('/max8/refpages/jit.uyvy2luma', 130),
 'jit.vcr': ('/max8/refpages/jit.vcr', 544),
 'jit.wake': ('/max8/refpages/jit.wake', 792),
 'jit.window': ('/max8/refpages/jit.window', 790),
 'jit.xfade': ('/max8/refpages/jit.xfade', 384),
 'js': ('/max8/refpages/js', 584),
 'jstrigger': ('/max8/refpages/jstrigger', 584),
 'jsui': ('/max8/refpages/jsui', 426),
 'key': ('/max8/refpages/key', 774),
 'keyup': ('/max8/refpages/keyup', 774),
 'kink~': ('/max8/refpages/kink~', 461),
 'kslider': ('/max8/refpages/kslider', 646),
 'lcd': ('/max8/refpages/lcd', 752),
 'led': ('/max8/refpages/led', 829),
 'levelmeter~': ('/max8/refpages/levelmeter~', 796),
 'line': ('/max8/refpages/line', 617),
 'linedrive': ('/max8/refpages/linedrive', 599),
 'line~': ('/max8/refpages/line~', 786),
 'listfunnel': ('/max8/refpages/listfunnel', 289),
 'loadbang': ('/max8/refpages/loadbang', 755),
 'loadmess': ('/max8/refpages/loadmess', 611),
 'log~': ('/max8/refpages/log~', 344),
 'lookup~': ('/max8/refpages/lookup~', 817),
 'lores~': ('/max8/refpages/lores~', 688),
 'makenote': ('/max8/refpages/makenote', 680),
 'match': ('/max8/refpages/match', 759),
 'matrixctrl': ('/max8/refpages/matrixctrl', 697),
 'matrix~': ('/max8/refpages/matrix~', 641),
 'maximum': ('/max8/refpages/maximum', 716),
 'maximum~': ('/max8/refpages/maximum~', 633),
 'mean': ('/max8/refpages/mean', 226),
 'menubar': ('/max8/refpages/menubar', 374),
 'message': ('/max8/refpages/message', 818),
 'meter~': ('/max8/refpages/meter~', 797),
 'metro': ('/max8/refpages/metro', 609),
 'midiflush': ('/max8/refpages/midiflush', 680),
 'midiformat': ('/max8/refpages/midiformat', 494),
 'midiin': ('/max8/refpages/midiin', 707),
 'midiinfo': ('/max8/refpages/midiinfo', 487),
 'midiout': ('/max8/refpages/midiout', 749),
 'midiparse': ('/max8/refpages/midiparse', 787),
 'minimum': ('/max8/refpages/minimum', 717),
 'minimum~': ('/max8/refpages/minimum~', 633),
 'minmax~': ('/max8/refpages/minmax~', 633),
 'modifiers': ('/max8/refpages/modifiers', 774),
 'mousefilter': ('/max8/refpages/mousefilter', 691),
 'mousestate': ('/max8/refpages/mousestate', 774),
 'movie': ('/max8/refpages/movie', 654),
 'mstosamps~': ('/max8/refpages/mstosamps~', 592),
 'mtof': ('/max8/refpages/mtof', 469),
 'mtof~': ('/max8/refpages/mtof~', 129),
 'mtr': ('/max8/refpages/mtr', 741),
 'multislider': ('/max8/refpages/multislider', 646),
 'mute~': ('/max8/refpages/mute~', 699),
 'mxj': ('/max8/refpages/mxj', 318),
 'mxj~': ('/max8/refpages/mxj~', 317),
 'next': ('/max8/refpages/next', 162),
 'noise~': ('/max8/refpages/noise~', 811),
 'normalize~': ('/max8/refpages/normalize~', 597),
 'notein': ('/max8/refpages/notein', 787),
 'noteout': ('/max8/refpages/noteout', 750),
 'nslider': ('/max8/refpages/nslider', 441),
 'number': ('/max8/refpages/number', 778),
 'number~': ('/max8/refpages/number~', 794),
 'numkey': ('/max8/refpages/numkey', 766),
 'offer': ('/max8/refpages/offer', 677),
 'omx.4band~': ('/max8/refpages/omx.4band~', 423),
 'omx.5band~': ('/max8/refpages/omx.5band~', 423),
 'omx.comp~': ('/max8/refpages/omx.comp~', 423),
 'omx.peaklim~': ('/max8/refpages/omx.peaklim~', 455),
 'onebang': ('/max8/refpages/onebang', 742),
 'onecopy': ('/max8/refpages/onecopy', 497),
 'onepole~': ('/max8/refpages/onepole~', 645),
 'opendialog': ('/max8/refpages/opendialog', 427),
 'oscbank~': ('/max8/refpages/oscbank~', 433),
 'out': ('/max8/refpages/out', 483),
 'outlet': ('/max8/refpages/outlet', 818),
 'out~': ('/max8/refpages/out~', 483),
 'overdrive~': ('/max8/refpages/overdrive~', 650),
 'pack': ('/max8/refpages/pack', 444),
 'pak': ('/max8/refpages/pak', 444),
 'panel': ('/max8/refpages/panel', 445),
 'pass~': ('/max8/refpages/pass~', 699),
 'past': ('/max8/refpages/past', 729),
 'patcher': ('/max8/refpages/patcher', 683),
 'patcherargs': ('/max8/refpages/patcherargs', 257),
 'pattr': ('/max8/refpages/pattr', 453),
 'pattrforward': ('/max8/refpages/pattrforward', 611),
 'pattrhub': ('/max8/refpages/pattrhub', 12),
 'pattrstorage': ('/max8/refpages/pattrstorage', 677),
 'pcontrol': ('/max8/refpages/pcontrol', 816),
 'peak': ('/max8/refpages/peak', 716),
 'peakamp~': ('/max8/refpages/peakamp~', 633),
 'peek~': ('/max8/refpages/peek~', 708),
 'pfft~': ('/max8/refpages/pfft~', 661),
 'pgmin': ('/max8/refpages/pgmin', 542),
 'pgmout': ('/max8/refpages/pgmout', 750),
 'phaseshift~': ('/max8/refpages/phaseshift~', 463),
 'phasewrap~': ('/max8/refpages/phasewrap~', 819),
 'phasor~': ('/max8/refpages/phasor~', 596),
 'pictctrl': ('/max8/refpages/pictctrl', 465),
 'pictslider': ('/max8/refpages/pictslider', 646),
 'pink~': ('/max8/refpages/pink~', 688),
 'pipe': ('/max8/refpages/pipe', 802),
 'playbar': ('/max8/refpages/playbar', 801),
 'play~': ('/max8/refpages/play~', 782),
 'plugphasor~': ('/max8/refpages/plugphasor~', 276),
 'plugsync~': ('/max8/refpages/plugsync~', 561),
 'poke~': ('/max8/refpages/poke~', 823),
 'poltocar': ('/max8/refpages/poltocar', 480),
 'poltocar~': ('/max8/refpages/poltocar~', 658),
 'poly': ('/max8/refpages/poly', 799),
 'polyin': ('/max8/refpages/polyin', 542),
 'polyout': ('/max8/refpages/polyout', 750),
 'poly~': ('/max8/refpages/poly~', 483),
 'pong~': ('/max8/refpages/pong~', 779),
 'pow': ('/max8/refpages/pow', 113),
 'pow~': ('/max8/refpages/pow~', 344),
 'prepend': ('/max8/refpages/prepend', 495),
 'preset': ('/max8/refpages/preset', 677),
 'print': ('/max8/refpages/print', 726),
 'prob': ('/max8/refpages/prob', 748),
 'pv': ('/max8/refpages/pv', 795),
 'pvar': ('/max8/refpages/pvar', 151),
 'qlim': ('/max8/refpages/qlim', 509),
 'qlist': ('/max8/refpages/qlist', 611),
 'qmetro': ('/max8/refpages/qmetro', 509),
 'quickthresh': ('/max8/refpages/quickthresh', 213),
 'radiogroup': ('/max8/refpages/radiogroup', 515),
 'rampsmooth~': ('/max8/refpages/rampsmooth~', 647),
 'random': ('/max8/refpages/random', 810),
 'rand~': ('/max8/refpages/rand~', 688),
 'rate~': ('/max8/refpages/rate~', 737),
 'receive': ('/max8/refpages/receive', 818),
 'receive~': ('/max8/refpages/receive~', 681),
 'record~': ('/max8/refpages/record~', 591),
 'rect~': ('/max8/refpages/rect~', 688),
 'regexp': ('/max8/refpages/regexp', 772),
 'relativepath': ('/max8/refpages/relativepath', 129),
 'reson~': ('/max8/refpages/reson~', 688),
 'rewire~': ('/max8/refpages/rewire~', 527),
 'round~': ('/max8/refpages/round~', 581),
 'route': ('/max8/refpages/route', 755),
 'router': ('/max8/refpages/router', 582),
 'rslider': ('/max8/refpages/rslider', 646),
 'rtin': ('/max8/refpages/rtin', 705),
 's': ('/max8/refpages/send', 611),
 'sah~': ('/max8/refpages/sah~', 586),
 'sampstoms~': ('/max8/refpages/sampstoms~', 592),
 'savedialog': ('/max8/refpages/savedialog', 594),
 'saw~': ('/max8/refpages/saw~', 688),
 'scale': ('/max8/refpages/scale', 599),
 'scope~': ('/max8/refpages/scope~', 794),
 'screensize': ('/max8/refpages/screensize', 603),
 'see Arithmetic operators': ('/max8/vignettes/thesaurus#arithmetic', 711),
 'see Boolean operators': ('/max8/vignettes/thesaurus#boolean', 410),
 'see Convert colorspaces': ('/max8/vignettes/thesaurus#colorspaces', 129),
 'see Draw': ('/max8/vignettes/thesaurus#draw', 265),
 'see Filters': ('/max8/vignettes/thesaurus#filters', 566),
 'see Sampling and audio buffers': ('/max8/vignettes/thesaurus#sampling', 74),
 'see Video mixing and compositing': ('/max8/vignettes/thesaurus#compositing',
                                      384),
 'select': ('/max8/refpages/select', 829),
 'selector~': ('/max8/refpages/selector~', 699),
 'send': ('/max8/refpages/send', 818),
 'send~': ('/max8/refpages/send~', 751),
 'seq': ('/max8/refpages/seq', 719),
 'seq~': ('/max8/refpages/seq~', 639),
 'serial': ('/max8/refpages/serial', 791),
 'setclock': ('/max8/refpages/setclock', 789),
 'sfinfo~': ('/max8/refpages/sfinfo~', 561),
 'sflist~': ('/max8/refpages/sflist~', 677),
 'sfplay~': ('/max8/refpages/sfplay~', 589),
 'sfrecord~': ('/max8/refpages/sfrecord~', 545),
 'sig~': ('/max8/refpages/sig~', 786),
 'sin': ('/max8/refpages/sin', 43),
 'sinh': ('/max8/refpages/sinh', 757),
 'sinh~': ('/max8/refpages/sinh~', 757),
 'sinx~': ('/max8/refpages/sinx~', 757),
 'slide': ('/max8/refpages/slide', 225),
 'slider': ('/max8/refpages/slider', 646),
 'slide~': ('/max8/refpages/slide~', 224),
 'snapshot~': ('/max8/refpages/snapshot~', 794),
 'spectroscope~': ('/max8/refpages/spectroscope~', 660),
 'speedlim': ('/max8/refpages/speedlim', 802),
 'spell': ('/max8/refpages/spell', 722),
 'spigot~': ('/max8/refpages/spigot~', 582),
 'spike~': ('/max8/refpages/spike~', 633),
 'split': ('/max8/refpages/split', 829),
 'spray': ('/max8/refpages/spray', 620),
 'sprintf': ('/max8/refpages/sprintf', 725),
 'sqrt': ('/max8/refpages/sqrt', 667),
 'sqrt~': ('/max8/refpages/sqrt~', 667),
 'standalone': ('/max8/refpages/standalone', 354),
 'stripnote': ('/max8/refpages/stripnote', 690),
 'strippath': ('/max8/refpages/strippath', 257),
 'stutter~': ('/max8/refpages/stutter~', 635),
 'substitute': ('/max8/refpages/substitute', 686),
 'suckah': ('/max8/refpages/suckah', 257),
 'suspend': ('/max8/refpages/suspend', 561),
 'sustain': ('/max8/refpages/sustain', 693),
 'svf~': ('/max8/refpages/svf~', 672),
 'swap': ('/max8/refpages/swap', 694),
 'swatch': ('/max8/refpages/swatch', 514),
 'switch': ('/max8/refpages/switch', 698),
 'sxformat': ('/max8/refpages/sxformat', 706),
 'sync~': ('/max8/refpages/sync~', 701),
 'sysexin': ('/max8/refpages/sysexin', 707),
 'table': ('/max8/refpages/table', 810),
 'tan': ('/max8/refpages/tan', 43),
 'tanh': ('/max8/refpages/tanh', 757),
 'tanh~': ('/max8/refpages/tanh~', 757),
 'tanx~': ('/max8/refpages/tanx~', 757),
 'tapin~': ('/max8/refpages/tapin~', 568),
 'tapout~': ('/max8/refpages/tapout~', 568),
 'techno~': ('/max8/refpages/techno~', 817),
 'teeth~': ('/max8/refpages/teeth~', 221),
 'tempo': ('/max8/refpages/tempo', 713),
 'text': ('/max8/refpages/text', 720),
 'thispatcher': ('/max8/refpages/thispatcher', 816),
 'thispoly~': ('/max8/refpages/thispoly~', 483),
 'thresh': ('/max8/refpages/thresh', 802),
 'thresh~': ('/max8/refpages/thresh~', 755),
 'timer': ('/max8/refpages/timer', 732),
 'togedge': ('/max8/refpages/togedge', 829),
 'toggle': ('/max8/refpages/toggle', 829),
 'tosymbol': ('/max8/refpages/tosymbol', 129),
 'touchin': ('/max8/refpages/touchin', 542),
 'touchout': ('/max8/refpages/touchout', 750),
 'train~': ('/max8/refpages/train~', 557),
 'trapezoid~': ('/max8/refpages/trapezoid~', 808),
 'triangle~': ('/max8/refpages/triangle~', 808),
 'trigger': ('/max8/refpages/trigger', 609),
 'tri~': ('/max8/refpages/tri~', 688),
 'trough': ('/max8/refpages/trough', 717),
 'trunc~': ('/max8/refpages/trunc~', 760),
 'ubutton': ('/max8/refpages/ubutton', 755),
 'udpreceive': ('/max8/refpages/udpreceive', 541),
 'udpsend': ('/max8/refpages/udpsend', 614),
 'umenu': ('/max8/refpages/umenu', 723),
 'universal': ('/max8/refpages/universal', 611),
 'unpack': ('/max8/refpages/unpack', 620),
 'urn': ('/max8/refpages/urn', 810),
 'uzi': ('/max8/refpages/uzi', 642),
 'value': ('/max8/refpages/value', 818),
 'vdp': ('/max8/refpages/vdp', 791),
 'vectral~': ('/max8/refpages/vectral~', 785),
 'vexpr': ('/max8/refpages/vexpr', 783),
 'vst~': ('/max8/refpages/vst~', 478),
 'waveform~': ('/max8/refpages/waveform~', 264),
 'wave~': ('/max8/refpages/wave~', 817),
 'xbendin': ('/max8/refpages/xbendin', 538),
 'xbendin2': ('/max8/refpages/xbendin', 538),
 'xbendout': ('/max8/refpages/xbendout', 612),
 'xbendout2': ('/max8/refpages/xbendout', 612),
 'xnotein': ('/max8/refpages/xnotein', 788),
 'xnoteout': ('/max8/refpages/xnoteout', 788),
 'zerox~': ('/max8/refpages/zerox~', 828),
 'zigzag~': ('/max8/refpages/zigzag~', 338),
 'zl': ('/max8/refpages/zl', 396),
 'zmap': ('/max8/refpages/zmap', 356),
 'zplane~': ('/max8/refpages/zplane~', 262),
 '|': ('/max8/refpages/bitor', 418),
 '||': ('/max8/refpages/logor', 829)
}